### ISSUE TITLE
Section for the tutorials à la OSLC primer

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/oslc-site-hugo#1]
One of the best parts of the old site was the tutorial section which contained multi-page tutorials, e.g. http://open-services.net/resources/tutorials/oslc-primer/

@brianking how do you see this implemented in the new site?

**Comment by brianking** [comment]
I think we'll just have to extend the theme we are using to support such a layout. We plan on making our own Hugo theme anyway to customise design and layout. I'll be working with some developers on this.

See also http://oslc.github.io/developing-oslc-applications/ which has existed independently for a while and has a similar layout.

The goal is to gather all the most important tutorials in one place on the new site with a consistent design and layout.

**Comment by brianking** [comment]
@gabrielfdac @jailandrade @LeoTrujillo The theme is going to have to support this as well.

**Comment by brianking** [comment]
TODO: @gabrielfdac to come up with basic design, but not a top priority.

**Comment by gabrielfdac** [comment]
https://xd.adobe.com/view/1dbb0fb7-a470-4359-81cd-9fd78f0cb6b9

Here's the link for the Tutorials design.

**Comment by brianking** [comment]
That's good for a first version.

We'll build it out with this tutorial to start with, and then make changes as needed.
http://oslc.github.io/developing-oslc-applications/

I think for the first pass, the navigation arrows are not needed.

I'll open a separate issue to get this implemented.

**Comment by jailandrade** [comment]
I will be working on this

**Comment by jailandrade** [comment]
I uploaded this resource post to master

**Comment by jailandrade** [comment]
I think this task it's done

**Comment by brianking** [comment]
Yes, closing. For any bugs or changes of this feature, open a new issue.
