### ISSUE TITLE
Resources Page Design

### ISSUE THREAD

**Issue by gabrielfdac** [OSLC/oslc-site-hugo#10]
https://xd.adobe.com/view/40014562-2b02-42ca-8a69-4da9a947ccba

Here the first draft of the Resources Page.

A few notes: 
1. There are two versions of what a Featured Resource could look like. The idea is to have it not only be on the top of the list (like the current version) but have some more attention and possibly not have it's summary cut out or shortened. However I couldn't decide between the two approaches and I had some preferring one or the other, since there wasn't a clear winner I thought it'd be appropriate to let you guys decide.

2. On the 2nd row of the regular resources (non-featured) I show what is my intent end result whenever the user hovers over one of the "cards", essentially what would happen is the top section with the name and icon of the category would reduce in size, giving space for more text and the full title, and at the bottom where you'd usually see the Author name and the post date, you'll see the _detail_ and _download_ buttons. Also the idea is to make the whole card move slightly up which is why the shadow at the bottom is a bit more prominent (small movements like this usually results on a good feeling when navigating, we can experiments with this a bit more when we start coding.

And perhaps by accident, I may have including some new functionality that is currently not in the current version, such as:
1. A search input. Here we could make the user able to filter by title or author.

2. Resource Author and Post date. If I'm contributing I wanna see my name there! Jokes aside could actually be a cool way to give credit to those contributing. The post date is available on a few cases but not all.

3. If you note on the Feature V2 I have some icons for a rating and number of comments. This is not really a suggestion just may be something that you guys might want, and in that case I had a peak of what that could look like.

Finally here I took an approach of using colors to discern the categories (icons was how it was done on the current version) which I think is a nice way for the user to quickly identify the categories quickly.

Let me know your thoughts and suggestions!

**Comment by brianking** [comment]
Fantastic, I think it looks great. For the Featured, I like the first one better. The contrast of the bottom bar looks nice.

For the other cards, I like the idea of hover but if it is hard to simulate that on mobile or if it will require more coding, then I wouldn't worry too much about hover. So maybe we can make the intro text shorter and still fit in author name and other information.

I like all your ideas in general. Search is something we'll need for sure. I'm hoping we can use the site search for this and just pass a parameter to limit to the resources section. Although ideally it would just filter the current view, but implementing that will depend on how much work it is.

For ratings and comments, again these features will depend on things like whether it is already built into the Hugo platform or if there are add-ons we can easily use for it. I would not prioritise writing something from scratch right now.

**Comment by gabrielfdac** [comment]
Got it.

For the mobile we would likely change things slightly anyway, and there is no hover on mobile, so we'd have to think of something else. I guess the point I'm trying to make is, having the hover doesn't limit our approach to mobile. And the extra coding that might go into something like this is often marginal and shouldn't set us back at all.

Yes, I wouldn't focus on things like comments either, but just thought I'd keep them in mind in case we want them.

I'll update the design so that the featured is the one you liked better.

**Comment by brianking** [comment]
TODO: @brianking to open issues to implement a) infinite scrolling, b) search functionality, c) filtering.

**Comment by brianking** [comment]
Closing this now. We can open new issues for whatever is outstanding.
