### ISSUE TITLE
Terms of Use Page

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#100]
Add a terms of use page. For reference, see existing page at:

https://open-services.net/terms/

**Comment by brianking** [comment]
@axelreichwein @rersch @jamsden @berezovskyi Any input on this one? We need something much more lightweight without IBM references.

Can be merged possibly with Privacy Policy page #101 ??

**Comment by gabrielfdac** [comment]
Anything new on this?

**Comment by jamsden** [comment]
Should https://github.com/OSLC/oslc-site-hugo/wiki/Creating-A-News-Post be added to https://github.com/OSLC/oslc-site-hugo/blob/master/user_guide.md?

**Comment by berezovskyi** [comment]
Now that we are an OASIS OP, they are taking care of that.
