### ISSUE TITLE
Privacy Policy Page

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#101]
Add a Privacy Policy page. For reference, see the current page:

https://open-services.net/privacy/

**Comment by brianking** [comment]
@axelreichwein @rersch @jamsden @berezovskyi Any input on this one? We need something much more lightweight without IBM references.

**Comment by rersch** [comment]
Do we need specific privacy policies at all? We could refer to the OASIS [https://www.oasis-open.org/policies-guidelines]. The majority of the listed policies do not apply, but if there are any critical issues they should be covered. 

We could create a policy page on open-services.net saying: open-services.net is the community platform of the OASIS OSLC member section and that OASIS policies (with the link) apply where applicable.

This should be good enough to start, if something is coming up later which require separate policies, 
we can still add them.

**Comment by jamsden** [comment]
The Privacy Policy needs to reflect the policies of the legal entity associated with open-services.net. That is the entity that might be subject to litigation from privacy issues. Who is that legal entity? OASIS? If so, then a link to OASIS policy guidelines associated with privacy policy should be sufficient. But I would guess OASIS may have some concerns about becoming involved in some legal entity. 

Perhaps we need some guidance from our lawyers.

**Comment by brianking** [comment]
@jamsden Who are "our lawyers"?

**Comment by gabrielfdac** [comment]
Anything updates?

**Comment by berezovskyi** [comment]
We also need to ensure GDPR compliance (not to set any cookies before consent)

**Comment by berezovskyi** [comment]
Now that we are an OASIS OP, they are taking care of that.
