### ISSUE TITLE
Author Links on Blog Posts

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#105]
1. Ensure that the correct author is accredited on blog posts moving forward. Is this taken from the github commit, or from somewhere else?

2. Fix the links on the current posts.

**Comment by jailandrade** [comment]
The author of the post both in news and resources is defined in the FrontEnd Matter with the tag/attribute `author`. For the old posts I can create a script to convert the html to markdown, to automatize this task.

**Comment by brianking** [comment]
As discussed on the call today, 2 work items here:

1. Add a tag to posts for author url, and use that as the hyperlink on the author's name
2. Ensure that the author name has the same size font as the date and comments text to the left and right, and that they all align horizontally.

**Comment by jailandrade** [comment]
This is ready to test in master

**Comment by brianking** [comment]
Link works, but author text is still too big. Inspection shows it is 22px while other text on that line is 20px.

**Comment by jailandrade** [comment]
I set a fixed font-size for the author name.

**Comment by brianking** [comment]
Font size looks consistent now, closing.
