### ISSUE TITLE
Implement Case Studies Page

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#106]
Issue #28 talks about the design (and content) of the Case Studies page.

This issue is to implement the theme for it based on the design:

https://xd.adobe.com/view/3f063148-9a3a-4143-bf33-fdf74ae577e7/

**Comment by LeoTrujillo** [comment]
Working on it

**Comment by LeoTrujillo** [comment]
@brianking now this page is working, it is in `/case-studies` if you want to check. These changes are already in master branch

**Comment by LeoTrujillo** [comment]
@gabrielfdac I finished the styles in this page but I need the images and to set them in the page, can you send me those images please?

**Comment by LeoTrujillo** [comment]
I added the case studies section in the home page and added a button to redirect a that page, please tell me what do you think. Just missing the images  to add them in each section, now I just added a sample image.
<img width="1440" alt="c" src="https://user-images.githubusercontent.com/3343042/29730774-3d81e474-89a7-11e7-943a-52971bef2ee7.png">

**Comment by brianking** [comment]
Content related -- re-use some content from here:
http://open-services.net/wiki/communications/Why-should-you-care-about-OSLC/

**Comment by jailandrade** [comment]
working on it

**Comment by berezovskyi** [comment]
@gabrielfdac shouldn't it be on the same page as https://open-services.net/why/

**Comment by berezovskyi** [comment]
No case studies at this time, will revisit later.
