### ISSUE TITLE
Implement the Tutorial resource theme page

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#107]
From issue #1, let's implement the Tutorial resource. The criteria are:

* It's a Resource, so has to be a sub-page of that
* A template exists that people can copy to create their own tutorial

**Comment by jailandrade** [comment]
The template is ready, although the search is still not implemented

**Comment by brianking** [comment]
2 things to do here:

1. Remove Search for now. File an issue to implement it later.

2. Video playback is not working.

![firefox_screenshot_2017-09-15t13-36-40 770z](https://user-images.githubusercontent.com/114116/30485024-741001b6-9a2c-11e7-8ca6-bb7185968b9e.png)

**Comment by jailandrade** [comment]
This task is ready to review in master

**Comment by brianking** [comment]
Reviewed and working. If you are comfortable tutorials are ready for prime time, please close this. Don't forget to open the issue about doing the search later.
