### ISSUE TITLE
Homepage Content

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#11]
Add initial content to the homepage. As laid out in the site plan, here is some guidance:

**Overview**
The home page will be split into sections that introduce different parts of the site/community. Where necessary, each section will link into different parts of the site.

**Sections**
Not necessarily in this order….
* Case Studies - targeting 3 audiences: 
  * Vendors of data handling software. Why OSLC is complimentary to their business model, and not a threat
  * Systems Integrators / Users of vendor software: Why OSLC will not disrupt their workflow, and add extra value on top
  * Developers
* About - very short paragraph, or carousel section, about OSLC
* News - some prominent news stories highlighted
* Contribute - show a use case or user story about contributing that then links into the Contribute page
* Resources - Explain how to get the most of the site if looking for OSLC resources, and where to find them
* Connect - icons / links to connect with us on social media and other channels

**Maps To**
This maps somewhat to the current homepage, however the sections must emphasise more the the site sections and not what the community does. There must also be more contrast between sections.

**Examples**
* http://ambassadors.onlab.us/
* https://developer.ubuntu.com/en/ 

**Related issues**
* #7 Homepage Design

**Comment by brianking** [comment]
The basic design is live now on the testsite - https://oslc.github.io/. There is some placeholder content in there for now, 

Here is some content I propose for the homepage, feedback welcome. cc @berezovskyi @jamsden @rersch @axelreichwein for input. If you know of any professional wordsmiths who might be willing to help, let me know. Please also comment if you have opinions about the ordering of the sections.

**Banner Text**
Title: Open Services for Lifecycle Collaboration
Subtitle: (Also known as the "OSLC" open community)
Text: We are a group of individuals and organisations that collaborate on specifications and software to make tool and data integration easier

**Stats Section**
(_Let's skip this for now, it might be removed_)

**Case Studies Section**
There are a number of OSLC solutions in the wild that illustrate the power of better integrations and data linkage. Explore with us a few of these.

(_underneath there will be sections targeting 3 audiences that will link to the Case Studies page_ - [reference](https://github.com/OSLC/oslc-site-hugo/issues/7#issuecomment-315762496))

**About Section**
(_first paragraph taken from [Vision](https://open-services.net/wiki/steering-committee/Vision/) - this might be too long_)
We live in a dynamic, rapidly changing global world awash in data and hungry for knowledge. Organizations are experiencing extreme pressures for digital transformations in order to collect, communicate, validate, reason about and act on this data for innovative new competitive opportunities. Addressing this pressure requires a flexible, efficient, and effective means of planning, building, operating, assessing and managing potentially complex, rapidly changing, integrated solutions. This in turn puts pressure on engineering and development organizations to utilize methods and tools supporting continuous engineering and continuous delivery in order to quickly respond to new opportunities and close the demand/supply gap.

OSLC is a gathering of cross-industry experts who explore common challenges to enable better software integrations. Our specifications are free to adopt, and we facilitate sample integrations. OSLC technologies are inspired by the Web, meaning they use open linked data standards, RESTful services, and base data connections on the power of the URL.  

Button: Learn more

**Contribute Section**
We have a variety of ways to get involved with the OSLC community. Whether you are a software developer, systems integrator, tool vendor or buyer, consultant, analyst, or open source enthusiast, there is value both in flexibility and cost savings of contributing to the community based around open interfaces.

Button: Contribute

**Resources Section**
Seeing is doing, so come and learn how to do things. In the resources section of the site, you will find various resources to help including tutorials, videos, articles, and presentations.

Button: Learn more

**News Section**
Read the latest updates from the around the community.

**Comment by rersch** [comment]
We need to point out very strongly at a prominent spot that we are working on integration solutions for engineering/development environments and not on SW integration in general. 
On place could be the text in the banner: e.g. "An open community building practical specifications to integrate data in engineering and SW development environments".  This is based on the old text, which I like better than the new proposal.
In the "About Section" proposal (taken from the vision), engineering and development is mentioned, but in the 2nd part talks also only "software integration". This should also be extended by "in engineering and development environments".

**Comment by rersch** [comment]
what I'm missing is a reference to the extended OSLC Eco system (Eclipse Lyo, OSLC on GitHub, OSLC on Codeplex, LinedData on W3C, and other communities. There should be a button, text or similar with a link to an Eco system page. This page should have an overview picture (similar, but better as attached) with the links to the other sites.
![oslc-eco](https://user-images.githubusercontent.com/29402426/28709941-90c0d702-7382-11e7-8739-1679f4a34b15.jpg)

**Comment by rersch** [comment]
will the part with the numbers (members, implementations, organizations) stay? 
If yes, where are these numbers coming from? The Eco system could be added here "Communities connected with us".
If not, maybe this spot could used for the reference to the Eco system.

**Comment by brianking** [comment]
@rersch in reply to your comments...

* Point taken about "in engineering and development environments". I'll be sure to clarify that in the content.

* Issue #35 is open about the ecosystem visualisation. We'll be updating the image, and also refreshing the text content. I propose that we put this in the About section of the site, either as a section on the main About page and/or and About sub-page. We'll also be highlighting some opportunities to participate in the wider ecosystem in the Contribute site section.

* We will probably remove the numbers section before launch. It was just an idea. Firstly, we don't have reliable ways of getting that data right now, and secondly they could be low numbers that don't provide much meaning.
An alternative might be to highlight the work of a community member.

**Comment by brianking** [comment]
Opened issue #158 to update the homepage content, and that takes precedence over this. So closing this now.
