### ISSUE TITLE
About - Vision and Mission Statement

### ISSUE THREAD

**Issue by m257645** [OSLC/oslc-site-hugo#111]
Here is something I would posit for consideration as the up front Mission and Vision sections portions of the About section.

**# Our Mission**
**## Mission**
The OSLC Community is intended to be an open community collaborating on integration challenges around lifecycle applications, capturing user scenarios for understanding and evolving related specifications for integrating software, and developing integration solutions and prototypes based on those specifications to share with the user community.
**## Vision**
The community is striving to pull together many diverse initiatives focused around application integration solutions to collaborate and partner with each other rather than compete. There are many organizations with different backgrounds sharing the vision of integrated engineering environments. Sometimes they are promoting different approaches than OSLC and linked data solutions but the goal of the community is to openly discuss complementary approaches which can also be appropriate with the goal of improving the overall viability of standards/implementations for supporting industry integration challenges.

_(then include a link to the entire Vision Statement for OSLC.)_

**Comment by brianking** [comment]
Thank you @m257645, will consider this for the About page when I update the content tomorrow.

**Comment by brianking** [comment]
This blurb is up, so closing this issue. We will decide how to fill out the content more of this page in issue #18.

Current test page:
https://oslc.github.io/about/mission/

**Comment by jamsden** [comment]
Re: vision/mission - vision describes some desired result, mission describes the effort used to achieve that desired result. 

http://open-services.net/wiki/steering-committee/Vision/ is a broader Future Vision statement from the OASIS OSLC Member Section Steering Committee.
