### ISSUE TITLE
Template for About Single page

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#114]
We are going to be having single pages under /about/. We need a template for these. single.html in the theme?

The first page you can add is mission.html

Also it would be nice to have separate directories for the following files, to better differentiate them.

* about content that is on the main About page (nearly everything that is in /about/)
* about sub-pages

**Comment by jailandrade** [comment]
Will be using the same design in the single.html that we are using in the about page?

**Comment by brianking** [comment]
Let's just go with a basic design right now with white background, that supports text and images at least.

**Comment by jailandrade** [comment]
So, the templates are ready, but need to match a given structure.

I use governance.md, people.md, mission.md, faq.md and organizations.md to enable the url on the subpage, so we can not delete or delete the category attribute of those files.

For the content in those pages I use the other markdown files in the content/about folder, you will notice that they have the tag for the content type and also the data in the FrontMatter, this is to avoid duplicate code with the about page.

**Comment by brianking** [comment]
@jailandrade Question:

What are the characteristics (I mean, what does the code look like) that makes a page iterative (i.e. adding another item to be appended like in the FAQ) vs. a static page (looks like Mission page is static right now, even though I see more than one Mission file in the content folder)?

I think we'll need both, dynamic and static, and I want to understand how to build both.

**Comment by berezovskyi** [comment]
@brianking what is an iterative page?

**Comment by brianking** [comment]
@berezovskyi A page built from different parts, i.e. separate files.

**Comment by jailandrade** [comment]
The subpage about/mission is a single post in Hugo, when you navigate to that link you are getting the contenf from `content/about/mission.md` file. You can access to all the posts in that folder if you appoint to `oslc.co/about/filename`.

For the FAQ, Brands, People and Organizations subpages I made a hack, which is iterate over all the posts in the `content/about` folder but only shows the ones with the corresponding tag, e.g: "faq"  

When you access to oslc.co/about/subpage you are using the themes/oslc/layout/about/single.html file which normally show only a single post but we use a hack you can display the posts whenever you want inside the about folder

**Comment by brianking** [comment]
Closing. Above comment will be adapted for documentation on adding content to the site.
