### ISSUE TITLE
Gather Testimonials for Quotes on About Page

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#115]
Near the bottom of the page at https://oslc.github.io/about/ we have a carousel of quotes. We should have at least 3 to start. They will feature:

* Your photo
* Name
* Company
* Quote

The quote should be something positive about your experience with OSLC. It can be a software integration problem that OSLC helped solve, a community experience, or something else relevant.

If you are interested in being featured, please comment here with your information

**Comment by brianking** [comment]
@berezovskyi we abandoned the carousel on the homepage, but is this something we could add to, for example, the Why page?

cc @axelreichwein

**Comment by berezovskyi** [comment]
@jadelkhoury do you think you are ready to talk about your OSLC use?

The project I am working on right now just begun and OSLC is not a finalised concept yet, I can't promote the use of OSLC in it until then.

I will ask Frederic as well.

**Comment by berezovskyi** [comment]
Do you think any of the vendors from http://open-services.net/software/ would be ready to give a testimonial? If not yet, maybe we should just wait with this section until later.

**Comment by axelreichwein** [comment]
I would be happy to provide a quote. But it would be good to get a few more, for example from OSLC Steering Committee members.

**Comment by brianking** [comment]
Here is a quote from our [2014 datasheet](https://github.com/OSLC/oslc-community/issues/16) that we may be able to re-use:

![quote2014](https://user-images.githubusercontent.com/114116/32553858-47fc1970-c498-11e7-948c-18212ea2f267.png)

**Comment by berezovskyi** [comment]
Not relevant now, will revisit later.
