### ISSUE TITLE
Gather Case Studies Content

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#116]
The test page is at:
https://oslc.github.io/case-studies/

These are more involved stories about the usage of OSLC technologies, with a couple of paragraphs and media included (pictures, charts, videos, ...).

They are from 3 viewpoints, and thus targeted at 3 different audiences:
* Users, i.e. data integrators
* Vendors, who support OSLC in their tools
* Developers, their experiences working with OSLC tech

The goal here is to show some positive experiences. We would like companies or organisations to be featured here, so be sure that your employer is comfortable with that.

**Comment by berezovskyi** [comment]
No case studies at the moment.
