### ISSUE TITLE
About Navigation

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#118]
Change the sub navigation items on About to point to sub-pages, and not to anchors on the page.

Also note the subtle design feature of the selected page, where it is underlined. 

You can see it here (and click around to see it working):

https://xd.adobe.com/view/5d59ec65-69ae-431b-b35c-933d16e4c61d/

**Comment by jailandrade** [comment]
I already implemented this feature in master

**Comment by brianking** [comment]
@jailandrade Excellent, thanks.

I found a bug. Go to https://oslc.github.io/about/ and there is no underline on any items. Hover over the sub-menu and the underline appears, but the menu bar jumps in size. 

There are a few ways to fix this:

1. We make the Mission page the home page for About, and have it underlined by default
2. Make the sub-menu bar slightly taller so that when the underline appears it does not jump 
3. Make the bar more subtle, so that it fits better under the text

I have a preference for the first option right now.

**Comment by jailandrade** [comment]
Sure, I implemented the option 1 to solve this.

**Comment by brianking** [comment]
Great, closing now.
