### ISSUE TITLE
New Theme Skeleton

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#12]
Build out the skeleton of our new theme. General approach should be:

* Build out basic features as per the documentation
* Use other themes as reference where necessary

As we implement the designs (separate issues), we can add theme features on top as needed.

As for the theme name, we can just use oslc-theme or something similar.

**Comment by brianking** [comment]
For references on what the theme will need to have, refer to both the designs being created in other issues as well as the design guidelines outline in issue #4

**Comment by brianking** [comment]
Being developed on the 'new-theme' branch:

https://github.com/OSLC/oslc-site-hugo/tree/new-theme

**Comment by brianking** [comment]
@jailandrade @LeoTrujillo What would you say the big pieces of the 'skeleton' are left to do?

**Comment by jailandrade** [comment]
The main news page and the individual news articles I think

**Comment by brianking** [comment]
@jailandrade Anything major outstanding here?

**Comment by jailandrade** [comment]
I didn't notice we have some bug with the styles in this page, I'm going to fix it

**Comment by brianking** [comment]
We have a couple more pages left, open as other issues, so am closing this one off now.
