### ISSUE TITLE
Fixes to News Section on Homepage

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#124]
Here is the homepage design:

https://xd.adobe.com/view/f5a37d61-fe4c-4a78-a114-b75c9cc2010c/

Notice some things in the version currently implemented vs the design.

1. The whole box is too tall. This looks like a combination of the image box being bigger, but definitely the text box is too tall.
2. The text needs to be clipped. At a certain length, it needs to be cut off and then ended with an ellipsis (...).
3. The headline text looks heavier than the mockup text
4. The headline should be a hyperlink to the story

Also, please clarify how to specify the image in the post so that it is used by the homepage boxes.

**Comment by jailandrade** [comment]
Latest changes done, since the design does not contemplate real data I made these changes.

It is really necessary to have the point number two, can't we have a button "read more" or something similar? I think it's more user friendly

**Comment by jailandrade** [comment]
Ok, after a little research we have ellipsis 

![image](https://user-images.githubusercontent.com/512046/29747841-f57caf66-8acc-11e7-9ca7-2fa063f52a5b.png)

**Comment by brianking** [comment]
I am not seeing the ellipsis on Firefox.

![firefox_screenshot_2017-08-28t19-12-03 819z](https://user-images.githubusercontent.com/114116/29789212-a8c96fc8-8c35-11e7-8e03-75f2a46f7b76.png)

**Comment by jailandrade** [comment]
I don't think it could work everytime in Firefox because the content has `overflow:hidden` property and a special property `webkit-line-clamp` that only works in Chrome. Also because we don't know and we can't controllate the content in the end, it's difficult to calculate what is the best approach to add ellipsis

**Comment by jailandrade** [comment]
I just upload a script to add the ellipsis, replacing the css class; now it works in Firefox.

**Comment by brianking** [comment]
Great, closing now.
