### ISSUE TITLE
Seed Resources

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#128]
Add at least 2 resources from each category, from the old site to the new.

**Comment by brianking** [comment]
Changes so far (live at https://oslc.github.io/resources/):

* Added 2 articles
* Added 2 videos
* Added 2 presentations
* Added 2 tools
* Removed all placeholder resources

TODO:

* Determine what tutorials to add
* Hunt for more recent resources to add

**Comment by berezovskyi** [comment]
We've got most of them https://open-services.net/resources/
