### ISSUE TITLE
Resources Page Changes

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#129]
Design for reference: https://xd.adobe.com/view/40014562-2b02-42ca-8a69-4da9a947ccba/

Please implement the following changes on the Resources page:

- [x] Crop the text of top featured box, when necessary. As you can see with the current post in there 'Debunking the OSLC Link-Only Myth', it shows all the text of the post and the box is taller than it should be (check design).
- [x] Fix the Details button in the featured box, it does not have the correct link
- [x] Remove the Download button on all boxes
- [x] Crop the main text in the boxes, showing an ellipsis (...) for overflow (check design) 
- [x] Align the boxes correctly under the featured box. There is some extra space on the right side, it does not align with the featured box.

**Comment by jailandrade** [comment]
![image](https://user-images.githubusercontent.com/512046/29747805-5c1b1d40-8acb-11e7-8b7a-c91674d035cf.png)

![image](https://user-images.githubusercontent.com/512046/29747808-71b931b4-8acb-11e7-8c16-401aedf4d372.png)

Those are screenshots showing the latest changes

**Comment by jailandrade** [comment]
I don't think it can work everywhere or everytime because the content but this is a solution to crop the content in resource posts with the ellipsis

![image](https://user-images.githubusercontent.com/512046/29747862-9624f162-8acd-11e7-88a3-e13036eb8e22.png)

**Comment by brianking** [comment]
Again, I can not see the ellipsis in Firefox (can in Chrome and Safari).

![firefox_screenshot_2017-08-28t19-19-50 212z](https://user-images.githubusercontent.com/114116/29789547-aa246714-8c36-11e7-8477-eb6a5c2122ae.png)

Everything else works!

**Comment by jailandrade** [comment]
Same as the ellipsis in the news section in Home, it's possible but I need to do it with JavaScript, let me see what can be done.

**Comment by jailandrade** [comment]
I just upload a script to add the ellipsis, now it works in Firefox.

**Comment by brianking** [comment]
It's not working on all boxes. Same now in Firefox and Chrome. Check the bottom row in this image.

![firefox_screenshot_2017-08-29t12-11-46 493z](https://user-images.githubusercontent.com/114116/29820222-1e7654d2-8cc4-11e7-9d47-494b9a08b59d.png)

**Comment by LeoTrujillo** [comment]
I finished with that problem and I tested in firefox, chrome and safari.

**Comment by brianking** [comment]
@LeoTrujillo I don't like the new solution for 2 reasons:

1. It cuts all text to the same length, which means that all the boxes have too much whitespace now.
2. Maybe it was happening before, but the bottom of some headings are clipped, e.g. is there is a lower case 'g' in the title. 

This image shows both issues:

![firefox_screenshot_2017-08-29t20-01-08 028z](https://user-images.githubusercontent.com/114116/29841391-95909730-8d05-11e7-96fe-797494f8c341.png)

**Comment by LeoTrujillo** [comment]
Ok, no problem I'm going to try with another way

**Comment by brianking** [comment]
@LeoTrujillo if it takes a while, then please revert back to previous state for now.

**Comment by LeoTrujillo** [comment]
ok, sure

**Comment by brianking** [comment]
TODO : fix ellipsis on boxes that lazily load with infinite scroll.

**Comment by LeoTrujillo** [comment]
I implemented a solution but I had to cover the last line of information and with css put the ellipsis because I tried to cover just a little part of that information but some letters looked weird because was missing a little part of that letter, so I chose that solution, I'm going to merge that change in master and let me know what do you think about it.
<img width="1078" alt="cap" src="https://user-images.githubusercontent.com/3343042/30494672-bc3c2dac-9a0e-11e7-8778-013afe83f6d9.png">

**Comment by brianking** [comment]
Great, thanks. I notice one thing on the boxes you scroll down to. The bottom of characters that go below the line are cut off. Look at the letter 'p' in the image I am attaching. However, let's call this 'good enough' for now, and close this out. I will open issues for what is remaining, but it is not a priority right now.

![firefox_screenshot_2017-09-18t09-35-14 181z](https://user-images.githubusercontent.com/114116/30536484-4bac2948-9c66-11e7-9dee-45cdc5f88fac.png)
