### ISSUE TITLE
News / Blog Design

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#13]
Let's keep it simple for now and have a basic design for:

* blog index page, using traditional post excerpts scrolling on a page
* post page

No need to add anything fancy, whatever is native to Hugo posts.

**Comment by gabrielfdac** [comment]
Here's the news page design

https://xd.adobe.com/view/d999f9bc-f845-4de9-9dc6-80d397ebbcb6

And the individual Posts

https://xd.adobe.com/view/7c0ebd40-d77c-4acd-8444-4555bc6da472

Let me know what you guys think!

**Comment by brianking** [comment]
I like it. Nice, clean, and simple.

**Comment by jailandrade** [comment]
I love it, good work

**Comment by m257645** [comment]
Looks good to me.

**Comment by brianking** [comment]
@gabrielfdac I am not sure about having the categories on the top, that won't scale. I'm not sure where else we can put them, except in the sidebar. But the individual post page does not have a sidebar.

**Comment by gabrielfdac** [comment]
@brianking won't scale in what sense? Unless you plan on having 20 categories in the future (which I would recommend against `:D) it shouldn't be too much of a problem. But we can also put them on the side.

The individual pages not having anything on the side is a way to keep the content clean and not distract the reader. Maybe we could put it at the bottom?

**Comment by brianking** [comment]
@gabrielfdac and I discussed scaling today. It means that there might be more than 10 categories, for example.

TODO: @gabrielfdac to design for a category drop-down instead.

**Comment by brianking** [comment]
Closing this now. We can open new issues for whatever is outstanding.
