### ISSUE TITLE
Site Search

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#133]
Implement site wide search.

I'm open to where the search box should be, but the header seems the most logical place.

**Comment by jailandrade** [comment]
Yep, I can put a search box in the header and create the /search page to render the results.

**Comment by brianking** [comment]
I tried this on localhost, and so far so good. Some observations:

* When you search with a blank box (no text), it returns no results. It should not allow empty searches
* When there are no results, tell the user. Right now it is just empty
* Some of the search results are for pages that do not exist. For example, try 'tasktop'. The top result points to:
http://localhost:1313/news/announcements/learn-more-about-tasktop-sync
... which does not exist on this site.
* It is not returning results for some things you would expect, e.g. 'brian' which is listed as author on some resources.
* It does nothing when you try and search a url, e.g. http://cnn.com
* Page would benefit from a little more information at the top above the results, e.g. show the search term, and the number of results. Example: https://www.villagevoice.com/?s=ellis%20island
* We might want to start thinking about pagination of results, but not a priority right now

**Comment by brianking** [comment]
@jailandrade What's the status here? Do we need to abandon current solution for new one?

**Comment by jailandrade** [comment]
yep, we could go without results pages and go immediately to the result

**Comment by brianking** [comment]
@jailandrade Can you post a status here please.

I just deployed to both live sites, and notice it is not working on either. It works on localhost.

Also, I ran 'node site.js' but it does not seem to have picked up changed I made (new partials + strings in content/_index.md).

**Comment by jailandrade** [comment]
I made a hack for this, you need to replace the content of `static-src/node_modules/lunr-hugo/lib/index.js` with the content of `static-src/index.js` and run again `node site.js`

**Comment by jailandrade** [comment]
It can be automated with each deployment, but now I see the last error you report it.

I think this commit can solve it https://github.com/OSLC/oslc-site-hugo/commit/3498a5778d5bb3ae24ddef80b4f7e213f9ec9542

**Comment by jailandrade** [comment]
The search is working now, the step when we replace content of `static-src/node_modules/lunr-hugo/lib/index.js` with the content of `static-src/index.js` only need to be done once after a clear installation. The run `node site.js` step is mean to be done with each change to the content

**Comment by brianking** [comment]
@jailandrade can you please add that information to the setup and deployment doc:

https://github.com/OSLC/oslc-site-hugo/wiki/Contributing-Setup

Then this can be closed after.

Great work!

**Comment by jailandrade** [comment]
@hectorsanchezmx can you add the steps to the deployment script?

**Comment by jailandrade** [comment]
I already added the steps in the documentation
