### ISSUE TITLE
Implement Homepage Theme

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#14]
After building the skeleton theme in issue #12 then take the homepage design from issue #7 and implement it.

**Comment by brianking** [comment]
@jailandrade Do you have an update on this? A screenshot of progress to share?

**Comment by jailandrade** [comment]
In the last merge, we update the resources section to make it mobile friendly

I'm still working on #34

**Comment by brianking** [comment]
@jailandrade @LeoTrujillo Some comments based on what we have so far vs what is in the [design](https://xd.adobe.com/view/f5a37d61-fe4c-4a78-a114-b75c9cc2010c/).

* Icon in top left is not hyperlinked to home page (should be on all pages)
* Items are not centered in the middle similar to the design, i.e. community stats, next sections, header section for resources, title for news.
* Once the other pages are ready, be sure to start linking to them from the homepage sections. e.g. Learn More and Contribute buttons, See all... link in Resources, Resources sections, and so on. 
* We are missing the Case Studies section. It is not part of the design yet, @gabrielfdac still needs to get to it. See my comment about it in issue #7. Maybe you can add some sort of placeholder for it for now?

Other than that, coming on very nice!

**Comment by LeoTrujillo** [comment]
Ok, I'm working on it

**Comment by LeoTrujillo** [comment]
@brianking What do you mean in the second point?, Can you send me a screenshot please?

**Comment by brianking** [comment]
@LeoTrujillo Sure, check out this picture. On the left is the live site, on the right is the design (scale not the same in both). I've drawn a line on both to show where alignment should be. There are a couple of differences in the live site.

1. Resources section header is not centered, but is on left of page because the content of that section spreads accross the whole page. 
2. The Statistics section contents are not spanning the whole middle section, they look too centered.

<img width="1778" alt="issue17alignment" src="https://user-images.githubusercontent.com/114116/28463366-54c4d846-6e20-11e7-9f8a-3acb1941c93a.png">

**Comment by brianking** [comment]
Another thing I noticed. The 'Learn More' button in the 'Inspired by the web' section should go to the About page, not Resources. Link to Resources should be in that section.

**Comment by LeoTrujillo** [comment]
I corrected those details and now the changes are already on master branch, let me know what do you think

**Comment by jailandrade** [comment]
@brianking have you checked this?

**Comment by brianking** [comment]
Yes we can close this out. For any homepage theme tweaks, we can open new issues.
