### ISSUE TITLE
Search in Resource Tutorial

### ISSUE THREAD

**Issue by jailandrade** [OSLC/oslc-site-hugo#144]
Create a search function for the resource tutorial. This function only need to mark the coincidences in the text. Look for the solution less complicated.

**Comment by berezovskyi** [comment]
Searching for .NET almost worked ("net" works but ".net" doesn't):

![image](https://user-images.githubusercontent.com/64734/47608801-e2ea6700-da33-11e8-838b-30ca6d73d350.png)
