### ISSUE TITLE
New Default Blog Post Banner Image

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#147]
Replace the current image. This is for the case where a post does not have any image. It should be in the template as well.

Criteria:

* Web-ready : Good resolution but a small file that loads quickly
* Not as tall - takes up less vertical space so you can see the text quicker without scrolling
* Scales better when it is previewed on the homepage and the most popular posts sidebar. I'm not sure if that will require code changes for those previews
* The picture should be related  in some way to Blogging/Writing/OSLC
* The picture should be free for use, open license

**Comment by jailandrade** [comment]
I added two images, `img/jan-kahanek-184676.jpg` y `img/sergey-zolkin-403.jpg`. In this commit I put the first one as a banner.

**Comment by brianking** [comment]
Great. A couple of questions:

1. Where did you get the images, and do we have a license to use them?
2. Can they be renamed? Something like news-default.png

**Comment by jailandrade** [comment]
From here https://unsplash.com/photos/E0Spm6XXn2Y and here https://unsplash.com/photos/g3O5ZtRk2E4, yes, we can rename it, and yes they have a free license https://unsplash.com/license

**Comment by jailandrade** [comment]
I rename the image to `news-default.png`

**Comment by brianking** [comment]
@jailandrade The picture is a bit big at 1.5MB. We need something smaller that loads faster. A couple hundred KB at most I would say. I would also try and reduce the height of the image.

**Comment by jailandrade** [comment]
@brianking I've successfully reduced the image size from 1.5mb to 315kb, I'll upload the changes
