### ISSUE TITLE
Update Blog Post Banner Images

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#148]
For blog posts that do have images, take the most appropriate one and add it as the banner image. This will mean:

* Download the image and adding it static/img/ in the repository
* Updating the banner meta tag on the post.

**Comment by berezovskyi** [comment]
I added a banner for a resource but the `themes/oslc/layouts/resources/single.html` still loads a random image.

**Comment by brianking** [comment]
How did you add it @berezovskyi ?

The image is not random. It is defined in each news item markdown file.

`banner = "img/news-default.jpg"`

This can be customized there, per post. I'm thinking of not showing it on the single page, because most posts don't have an image and it is just taking up too much space. We can still show in in the preview on the homepage and the news index page.

**Comment by brianking** [comment]
My last comment referred to /news posts @berezovskyi. I now see you were talking about resources. I think you change in #165 now fixes resources/ posts as well. Let me know.

**Comment by brianking** [comment]
It turns out none of the old posts have images in them, so this is WONTFIX. Closing.
