### ISSUE TITLE
Social Sharing Updates on Blog

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#149]
You can share posts in 2 places, on the blog summary page and the individual post page. Please make the following changes to both.

* Remove G+
* Add LinkedIn
* Add Email
* Sharing window should be a new popup window, not opening in the same tab

**Comment by LeoTrujillo** [comment]
The share button in oslc new is working
<img width="1434" alt="c" src="https://user-images.githubusercontent.com/3343042/30756235-76523026-9f8f-11e7-8f16-f7a7e8d157a2.png">

**Comment by brianking** [comment]
It's not working for me, I get this error:

<img width="782" alt="issue149_fb_sharing_error" src="https://user-images.githubusercontent.com/114116/30760940-ab3db358-9fdc-11e7-8f6b-b4f2934b23f6.png">

**Comment by LeoTrujillo** [comment]
Ok, let me check

**Comment by LeoTrujillo** [comment]
Waiting a few minutes and test it again, I had to make public the koneksys app from facebook for to this works

**Comment by brianking** [comment]
Works now. It's showing an old image, but that might be a Facebook cache image though.

**Comment by brianking** [comment]
@LeoTrujillo Not sure if you closed this by accident, but this issue is not just about Facebook sharing. See original issue description. Reopening.

**Comment by LeoTrujillo** [comment]
The changes are already in master branch and them are working

**Comment by brianking** [comment]
Confirmed working, now deployed to oslc.github.io.
