### ISSUE TITLE
Check Font and Font Size in Banner Text

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#150]
On the following pages, check the font being used in the banner and the font sizes. Check both the header and description text. Looking closely, it seems some pages are different than others.

* Resources
* Contribute
* News
* About pages

**Comment by jailandrade** [comment]
I reduced the font size for the description in the banner for all the pages.

**Comment by brianking** [comment]
@jailandrade were my latest comments addressed already?

**Comment by jailandrade** [comment]
yes, I already submit my changes to this issue

**Comment by brianking** [comment]
Done, closing.
