### ISSUE TITLE
Setup Working Groups Site Section

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#151]
Similar to the current http://open-services.net/workgroups/, we need a space on the new site for working group landing pages. For full details of how WGs will work, see issue #146.

The tasks for this issue are:

- [x] Setup index page at /workgroups/, with templates and infrastructure to easily add new workgroups as markdown files
- [x] Markdown template for new groups
- [ ] Document how to add a new group (both the site page, and the other infrastructure - Discourse and Github)
- [x] Add first group page: https://github.com/OSLC/lifecycle-integration-patterns
- [x] Update the Working Groups box on the Contribute page

**Comment by jailandrade** [comment]
I added support for working groups

**Comment by brianking** [comment]
Anything left with WGs, please open a new issue. Closing this now as the basic infrastructure is setup.
