### ISSUE TITLE
Dynamic baseURL or default to oslc.so

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#155]
Currently the value is:

baseURL = "https://oslc.github.io/"

This causes problems when we deploy to oslc.co. So we have 2 options:

1. Stop deploying to GH and deploy to oslc.co exclusively
2. Change value at deploy time to oslc.co

Is there any value in deploying it to two places?

**Comment by jailandrade** [comment]
I think it's better to deploy to oslc.co exclusively to avoid duplication of issues and fixes

**Comment by hectorsanchezmx** [comment]
I agree with @jailandrade, the only benefit I see from deploying to oslc.github.io is using it as a test environment, but it's a static site, there really isn't much to test

**Comment by brianking** [comment]
This has been changed to just "/", but it broke social sharing links which is being investigated in issue #166.

Keep an eye out for possible other breakage.

**Comment by brianking** [comment]
This was resolved by adding the command line option '-b http://oslc.co/' to our deploy script. Which means we can continue with '/' for local testing. oslc.github.io is not loading correctly now, but this is being decommissioned. 

Closing.
