### ISSUE TITLE
Download and optimize images for the banners

### ISSUE THREAD

**Issue by jailandrade** [OSLC/oslc-site-hugo#156]
Right now we're using high resolution images hosted in unsplash, the problem with this is the loading time. We need to download those images from unsplash, resize and save for the web.

**Comment by brianking** [comment]
Images should be in KB (a few hundred or less), not MB.

**Comment by brianking** [comment]
@jailandrade is this done?

**Comment by jailandrade** [comment]
Yes, this is already done, if we continue using unsplash images we have to resize to 2000px width

**Comment by brianking** [comment]
Ok, closing. We are still using unsplash in other places, so I will open a new issue for that.
