### ISSUE TITLE
New Categories Dropdown Issues

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#157]
There are 2 issue (at least I see in Firefox):

1. Clicking on the arrow does nothing. The menu only open when you click on the text.
2. The items are cramped together, too little space. It seems like styles are missing. Look to Resources filter dropdown as a better example. Try to standardise look and feel of all dropdown on the site.

**Comment by jailandrade** [comment]
I fixed the arrow but I think I can't style the options in the select, I've found this comment about edit _options styling to select option is very much limited as to maintain a coherence and consistency among all the application in the operating system thus the browser are ought to restrict the style of some basic elements like in your case option tag.

The restriction depends browser to browser, like padding and even margin of option tag works in the mozilla firefox while it doesn't works with chrome_

**Comment by brianking** [comment]
It looks better now, even the spacing. I'm guessing on the Resources page, it looks different only because of the colour now. Can you confirm that there is no extra styling applied to that one?

**Comment by jailandrade** [comment]
I applied margin to other options, I think only works on Firefox.

**Comment by brianking** [comment]
Good enough for now!
