### ISSUE TITLE
Implementations Page

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#159]
We really need to show what real-world software is out there using OSLC. We currently have the [software page](https://open-services.net/software/), but as-is it has little utility and gets out of date easily.

New page should:
* have 2 columns, one for native support and one for adapters
* Have meaningful information about the implementation behind the links
* Have clear instructions about how to update the page (github pull request)

**Comment by brianking** [comment]
Inspiration:
http://fmi-standard.org/tools/

**Comment by brianking** [comment]
@berezovskyi @rersch @jamsden @axelreichwein 

Any feedback on this one?

**Comment by berezovskyi** [comment]
1. I really like the tool compat graphics as in http://open-services.net/software/accept360/
2. I think the list is still up to date, but adaptors might no longer be compatible with the newer versions of the tools.
3. FMI page is very cool, but we need a bit more data and implementation work to show off like they do: I don't know of any OSLC 3 implementations yet; many implementations have a flimsy Selection Dialog that is still very much a vendor lock-in.

I would suggest to create a http://www.redotheweb.com/DependencyWheel/ out of the data behind  http://open-services.net/software/ as a start.

**Comment by gabrielfdac** [comment]
Agreed

**Comment by gabrielfdac** [comment]
Didn't mean to close it

**Comment by berezovskyi** [comment]
wow, the FMI page just got better over the last 12 mo

**Comment by berezovskyi** [comment]
Will promote implementations individually until they warrant a separate showcase page.

PS: FMI page still kicks ass
