### ISSUE TITLE
Redo Homepage Images

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#161]
Very recently, in issue #158, the homepage content was refreshed. As part of that, some new images were added. This issue is to review the images, and replace them with more more appropriate and/or better designed one.

More details to follow.

**Comment by gabrielfdac** [comment]
https://xd.adobe.com/view/6b6de46d-b52f-4a67-820c-5f84b1e5f925/

Here's the current design for the first 3 images.

Images 1 and 3 have two options.

On image 1 I believe the second option has a more clean and understandable layout. However we need to be sure the change doesn't break any "hierarchies".

**Comment by brianking** [comment]
@axelreichwein Can you check images 1 and 3 to see if they are representative.

**Comment by axelreichwein** [comment]
I like image #3 with the colors. I have no preference between image #1 and #2, however, the boxes and the lines needs to stand out more.

**Comment by brianking** [comment]
What's the status of this @gabrielfdac ? To me it looks like:

* Hypermedia API image needs to be done
* Ecosystem image is in the works in issue #35 
* Solutions image needs to be done / optimised for this page

**Comment by gabrielfdac** [comment]
1 - Since that image was a newer image I had the impression it was not going to be redone. What is the idea for that one?

2 - Yes, I think a decision has to be made so that this unblocks. (As discussed in #35)

3 - Same as 1.

**Comment by brianking** [comment]
1. It is actually a cropped version of this image:
https://koneksys.com/img/Custom_vs_Discoverable.png
So at the very least, the image degraded in quality when I made it and would need to be redone. It is also too small compared to the other new images.

2. Will follow-up in that issue.

3. What information do you need to unblock? I think the image itself is fine here. However, it is sized bigger than it is, which makes it look grainy.

**Comment by gabrielfdac** [comment]
1 - If we need any alterations is fine. I can also recreate a image with higher resolution. What would be best?

3 - So just an overall reduction in size or a higher resolution version, right?

**Comment by brianking** [comment]
1. Yes higher res, but still small enough for quick loading

3. Right.

**Comment by gabrielfdac** [comment]
Images for "Hypermedia API" and "Solutions" have been updated and are currently on master

**Comment by gabrielfdac** [comment]
This issue has already been completed, closing
