### ISSUE TITLE
Redo Homepage CSS

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#162]
As part of issue #158 and especially with commit 84ea78a there are some hacks to style the sections on the homepage. We mostly use an existing class (.sec-case) and sub-classes in home.scss. (.sec-case2) was created just to give the alternating bg colour. There are two tasks in this issue:

- [x] Create a new class or classes to handle the sections on the homepage, with pretty descriptive names so they are easily identified.
- [x] Remove any old styles that were part of the previous iteration of the page, and are not used anymore.

**Comment by gabrielfdac** [comment]
New styles consists of
```
.section--story {
   .story {
      .story--content { }
      .story--image { }
      .story--button ( )
   }
}
```
With that the end markup ends up looking somewhat like this:
```
<div class="story">
  <div class="container">
    <div class="story--content">
      <!-- Titles and paragraphs -->
      <!-- Paragraphs *don't* need a wrapping <div> -->
    </div>
    <div class="story--image">
        <!-- Image(s) -->
    </div>
    <div class="story--button">
        <!-- "learn more" button -->
    </div>
  </div>
</div>
```

**Comment by brianking** [comment]
I checked out the branch, and it looks good to me. Feel free to go ahead and merge. I like how the text is now left aligned, but everything else is centered.

**Comment by gabrielfdac** [comment]
Change completed and merged
