### ISSUE TITLE
Social Sharing Widget Changes

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#166]
A few things here:

- [x] Fix urls to use baseURL global instead of hardcoded url
- [x] Replace 'Look this awesome post' when sharing to LinkedIn. Replace with a customizable summary, retrieved from metadata of post
- [x] Add Title of post when sharing to Twitter, before the url
- [x] For Twitter, after the url add 'by @Koneksys' which might lead to more clickthroughs and follows.
- [ ] Update old News posts to add summary to posts
- [x] Update Resource posts to add summary to posts
- [ ] Setup Facebook App for OSLC sharing
- [x] Consider putting the widget into a partial for re-use, instead of it being coded in 3 places (news single post and list, resources post)

**Comment by brianking** [comment]
After changing the baseURL in config.toml, the links being sent from the social share widget do not resolve correctly. I switched to using Permalink, same issue. It is the only place where I can see it not working right now

**Comment by brianking** [comment]
@jailandrade can you have a quick look at why permalink is not working here please.

**Comment by jailandrade** [comment]
It's weird, I test in oslc.co and it works for me, in different browsers

**Comment by brianking** [comment]
Indeed weird. Can you send me a screencast of it working @jailandrade ?

**Comment by jailandrade** [comment]
![image](https://user-images.githubusercontent.com/512046/31950455-3fe7bc10-b8a1-11e7-9129-6628fdf8bb4d.png)

![image](https://user-images.githubusercontent.com/512046/31950473-4a84c3ac-b8a1-11e7-9550-e67bac2e9dc8.png)

![image](https://user-images.githubusercontent.com/512046/31950500-59c9b7dc-b8a1-11e7-95ea-acafaa0f8297.png)

**Comment by brianking** [comment]
I'm going to close this and open new issues for what is remaining.
