### ISSUE TITLE
Update Resources Sharing Options

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#167]
Similar to what we did with News posts in issue #149 we need to update the sharing options on Resources pages.

**Comment by jailandrade** [comment]
I just integrate the share options here, I don't know if you have the correct app id for the facebook plugin @brianking

**Comment by brianking** [comment]
Fixed now, the resources page now uses the new post-share.html partial. If we need a new facebook app id, we should open a new issue for it.
