### ISSUE TITLE
Content Handlers and Redirects

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#169]
For oslc.co for now....

We need a couple of things setup on the server:

1. The server needs to send the right content type for certain types of content for the browser to display it.
e.g. application/rdf+xml for RDF files.
e.g. file: http://oslc.co/ns/cm/cm.rdf

2. Redirects need to work.
Right now I copied the site .htaccess from ns/ to a new ns/ folder on the new site. You can see it at:
https://github.com/OSLC/oslc-site-hugo/blob/master/content/ns/.htaccess

Maybe .htaccess is being ignored right now?

cc @jamsden @berezovskyi

**Comment by brianking** [comment]
.htaccess is not working because it is not there! It is not being added during the deployment to oslc.co. This would need to be fixed first.

**Comment by brianking** [comment]
Any update on this @hectorsanchezmx ?

**Comment by hectorsanchezmx** [comment]
.htaccess does not work in NGINX, I have added the redirects to the NGINX server block, but need to test the redirections, do we have the content on oslc.co to do that?

**Comment by berezovskyi** [comment]
Let's start with this:

http://oslc.co/ns/core -> http://oslc.co/ns/core/core.rdf iff the format requested is `rdf/xml` (later would be good to add `text/tutle` and still force `rdf/xml` reply or convert all files via Jena command line tools)

http://oslc.co/ns/core -> http://oslc.co/specifications/archive/core-2.0/ (will have to be http://oslc.co/specifications/archive/core-2.0/vocab/ in the future, but that's the problem for #194)

**Comment by berezovskyi** [comment]
@hectorsanchezmx the redirect does not work yet, but the homepage is redirecting to http://oslc.co/specifications/vocabularies/

**Comment by brianking** [comment]
The homepage redirect is fixed now.

@hectorsanchezmx Can you please document the redirects you setup, and other nginx changes, so that someone coming in to take over will be able to understand.

**Comment by berezovskyi** [comment]
From #214, we need to ensure proper redirects from HTTP to HTTPS URLs too.

**Comment by gabrielfdac** [comment]
@berezovskyi no, he's no longer working at koneksys. I'll reassign the issue

**Comment by berezovskyi** [comment]
all redirects are now handled in https://github.com/OSLC/oslc-site-content-negotiation
