### ISSUE TITLE
Fix and improve the mobile experience

### ISSUE THREAD

**Issue by gabrielfdac** [OSLC/oslc-site-hugo#171]
After investigation there are several issues that needs fixing or improvements for mobile.

Those include image sizes, layout, font sizes and other issues. This will mostly include CSS changes but does not exclude markup changes if necessary.

**Comment by gabrielfdac** [comment]
*Some Changes pushed*
Mobile specific:
• `Homepage` images no longer expand out of bounds;
• `Homepage` news section has been fixed, previously elements where too thin;
• `Notification-bar` font-size reduced to occupy less space;
• `Header` has seen many improvements:
   1 - Position has been fixed so that it doesn't cover the notification bar;
   2 - On mobile the Search functionality is now inside the menu;
   3 - Now when expanded the menu covers the entire screen;
   4 - Size has been tweaked for better overall feel.
• header.js which controls the menu feature for mobile was un-accessible on any page other than home. Source tag fixed.

All screen sizes:
• `All pages` margin between first content section and header have been improved;
• `Header` logo update and a few css tweaks;
• `Header` now has a subtle shadow to improve visibility over white background content.

This does _not_ cover all required improvements.

**Comment by brianking** [comment]
Is this done @gabrielfdac ?

**Comment by gabrielfdac** [comment]
Yes I think we can close it. Any other problems or fixes that pop up could just go to new and more specific issues.

**Comment by brianking** [comment]
Closing.
