### ISSUE TITLE
Style Specification Pages

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#172]
Add style for the following pages:

http://oslc.co/specifications/
http://oslc.co/specifications/vocabularies/

In particular:

* Consider adding a banner for consistency with other pages (not compulsory)
* Minimal table styling
* Check rest of the text is consistent with site

**Comment by brianking** [comment]
I just looked at your branch for this @gabrielfdac and it looks good, please merge into master.

**Comment by gabrielfdac** [comment]
Closed by merge
