### ISSUE TITLE
Fix Broken Links When Sharing

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#174]
When sharing certain resources (News pages, Resources, Working Group pages) on social media, the link being sent to the service is relative instead of being the whole url. This happened when we changed the base URL.

![sharinglinks](https://user-images.githubusercontent.com/114116/32443302-ccca05cc-c2fe-11e7-8b36-439b9adb4d4b.png)

**Comment by brianking** [comment]
Some relevant discussion here:
https://discourse.gohugo.io/t/solved-what-should-be-used-for-the-value-of-site-baseurl/5896

As far as I can see, leaving baseURL blank or setting it to "/" will just break some things and there is no way around it.

**Comment by jailandrade** [comment]
I'll check, I'm working on this issue now

**Comment by brianking** [comment]
Fixed this by adding the baseurl parameter when running Hugo in the deploy script.

`hugo -b http://oslc.co/ -t oslc`

Closing.
