### ISSUE TITLE
OSLC Examples

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#177]
Placeholder for interactive examples on the site. Replace this content with a description.

**Comment by axelreichwein** [comment]
Examples of intradisciplinary scenarios: 

- integration of requirements across different software applications, 
- integration of PLM info across different PLM systems

Example of interdisciplinary scenario: 

- integration of PLM and ALM info across different systems
- integration of PLM and ERP info across different systems

**Comment by jamsden** [comment]
Probably not needed for launch. Best examples are eclipse/Lyo reference implementations and Bugzilla samples, IBM's Continuous Engineering tool suite, Tasktop Lifecycle Integration Adapters, Koneksys apps, MID Smartfacts, etc.

**Comment by gabrielfdac** [comment]
@jamsden Good to have some suggestions. And I do believe it is super important to have examples to better illustrate OSLC.

We will definitely revisit this after launch.

**Comment by gabrielfdac** [comment]
Old issue, and doesn't take into account the latest content. If this is still an issue a new one should be created with updated criticism/content. Closing
