### ISSUE TITLE
Changes on Contribute Page

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#178]
- [x] New image in 'Join the Conversation' box.
- [x] Replace unsplash images
- [x] Possibly replace links with buttons

**Comment by gabrielfdac** [comment]
Ready for review on branch "OSLC-178"

**Comment by brianking** [comment]
I checkout out the branch. Comments:

* I like the buttons! However, can they scale? e.g. if we add more links to the coding section.
* 'Join the Conversation'. I don't see an image in there ... is it on purpose?
* Do other sections possibly need images?
* You are trolling me with the Evangelise image ;)
* I'm expanding the scope of this issue, and will add a couple of more tasks. Namely:
  * Add a specifications box
  * Change name of 'Add Content' box to 'Add to this Site'

**Comment by gabrielfdac** [comment]
Comments addressed and merged to master.

**Comment by gabrielfdac** [comment]
Old issue, no longer relevant, closing
