### ISSUE TITLE
404 Not Working on Digital Ocean

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#180]
Compare:

1. https://oslc.github.io/jinkies
2. http://oslc.co/jinkies/

Our customised 404 page is working on the first, but not on the second. Is this something that has to be configured on nginx?

**Comment by hectorsanchezmx** [comment]
I've set the 404 template to show, however this is still not working. I'll double-check the configuration for Hugo

**Comment by brianking** [comment]
Any further updates on this @hectorsanchezmx ?

**Comment by gabrielfdac** [comment]
Done. Closing
