### ISSUE TITLE
Purge About root page content

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#184]
http://oslc.co/about/ still has content. We don't need that page, so there are 2 tasks:

- [x] Remove the content on the page to trim down the codebase. Make sure first it is not being used elsewhere
- [x] Redirect /about/ to /about/mission/.

**Comment by jailandrade** [comment]
I was looking for a solution to redirect pages in Hugo but I can't find anything https://discourse.gohugo.io/t/url-redirect-forwarding/4689/16

I think it's something for the nginx configuration to make the redirect, maybe @hectorsanchezmx can help in this issue

**Comment by brianking** [comment]
As issue #191 was opened for the redirect, closing this one now.
