### ISSUE TITLE
More FAQ Questions

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#185]
1. Why aren't OSLC specifications W3C standards?
2. What is the relationship between OSLC specifications and W3C standards?
3. What is the difference between OSLC and openAPI/Swagger?
4. What is the difference between OSLC and microservices?
5. What is the difference between OSLC and Open Data Protocol (OData)?
6. What is the difference between OSLC and GraphQL?
7. What is the difference between OSLC and smartAPI?
8. What is the difference between OSLC and a SPARQL endpoint?
9. What is the difference between RDF and JSON?

**Comment by berezovskyi** [comment]
There is another question I get often from the people in ALM/PLM, but on the operational side: how can OSLC deal with the inefficiencies and overhead of RDF compared to binary-oriented standards such as OPC-UA.

Now I had a question at the last IoT conference I attended on how OSLC compares to the W3C WoT.

Re §4 & §9: these things need to be given a prominent place in the marketing material in general.

**Comment by brianking** [comment]
I welcome pull requests on any of these, or just answering here in the issue and I can add.

https://github.com/OSLC/oslc-site-hugo/wiki/Adding-a-FAQ-Entry

**Comment by gabrielfdac** [comment]
Do we need any more questions than we currently have? http://oslc.co/about/faq/
@berezovskyi @axelreichwein

**Comment by berezovskyi** [comment]
Yes, the classical one: "My question is not address here. Where is the best place to ask it?".

**Comment by gabrielfdac** [comment]
Good one, should we point to the discourse as a place to ask it? Or any other idea?

**Comment by berezovskyi** [comment]
Yes, Discourse is the best place.

**Comment by gabrielfdac** [comment]
Got it. I'll add that myself! Thanks @berezovskyi

**Comment by jamsden** [comment]
We have some entries now, more is always better. Suggest this not block site launch.

**Comment by gabrielfdac** [comment]
Current progress sufficient for Launch. New entries should be tracked on new issues. Closing.

**Comment by brianking** [comment]
Looks good. One suggestion I would make is to put the last question 'Is your question not addressed here?' at the top, perhaps in some sort of info box to distinguish it from the other questions.

**Comment by gabrielfdac** [comment]
Good suggestion. I'll revisit it once more pressing issues are dealt with.
