### ISSUE TITLE
Make Why OSLC a top-level page and menu item

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#186]
As discussed in issue #6 we will make the 'Why OSLC?' page a top-level page (not under About), and also add it as a top-level menu item.

- [x] Make top-level page
- [x] Add item to main site menu

**Comment by jailandrade** [comment]
I made the changes for this issue but I didn't upload to master, I created the branch https://github.com/OSLC/oslc-site-hugo/tree/issue-186 for these changes

Also I didn't delete the _Why_ page in the about submenu

**Comment by brianking** [comment]
This is done. Closing.
