### ISSUE TITLE
Getting Started page

### ISSUE THREAD

**Issue by axelreichwein** [OSLC/oslc-site-hugo#187]
Most persons interested in OSLC want to find resources on how to get started. Therefore, we need a "Getting Started" page, made visible through a top-level menu item.

The section can refer to all videos/articles/code examples which are useful when getting started. For example, it should refer to general documentation on REST APIs, and Linked Data, before introducing more specific OSLC concepts.

**Comment by brianking** [comment]
I don't think it is advisable to add yet another top-level menu item, it's getting too crowded. We should start thinking about sub-menus.

**Comment by gabrielfdac** [comment]
@jamsden agree, I'll remove the tag. Also I'd also argue whether or not this is actually needed. Not closing for now but we could eventually discuss this.
