### ISSUE TITLE
Unpublish oslc.github.io Pages and create production branch

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#192]
We want to unpublish the oslc.github.io pages, but still use the repository to push to from this repository, and pull from on Digital Ocean when deploying. It seems like we can only unpublish by deleting the master branch.

https://help.github.com/articles/unpublishing-a-user-pages-site/

I propose we create a production branch and use that. We should push to it fresh after a Hugo site generation, to get rid of extra cruft that might have got in the repository over time.

We need to:

a) Change our sub-module that we are using in the oslc-site-hugo repository. Right now we are using master:

`git submodule add -b master git@github.com:OSLC/oslc.github.io.git public`

Details in the 'Code and Content Setup' section at:
https://github.com/OSLC/oslc-site-hugo/wiki/Contributing-Setup

b) Setup the production branch on Digital Ocean to pull from production and not master.

**Comment by berezovskyi** [comment]
Why not just delete the master branch and push it again? Unless we choose the branch here https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#default-source-settings-for-repositories-without-the-username-naming-scheme the site should not get republished.

**Comment by brianking** [comment]
If that works, sure.

**Comment by hectorsanchezmx** [comment]
I've created the production branch, we now need to delete the master branch and set the production branch as default.

**Comment by berezovskyi** [comment]
is auto-deploy already working?

**Comment by berezovskyi** [comment]
to DO that is

**Comment by brianking** [comment]
@hector, I need to update deployment instructions and make sure everyone updates their repository. Once I figure it out, I will inform everyone and you can go ahead and delete master.

@berezovskyi Here is our current deployment instructions. 
https://github.com/OSLC/oslc-site-hugo/wiki/Contributing-Setup
What do you mean by auto-deploying? On every commit?

**Comment by hectorsanchezmx** [comment]
Alright @brianking, i'll keep an eye out for when you do the change.

**Comment by berezovskyi** [comment]
@brianking yes, on every merge to some branch (master/prod)...

I used the following Flask service for my Pelican blog on Bitbucket (I know, kinda not the same thing as GH and Hugo): https://gist.github.com/berezovskyi/52463a3ae61ea019b52dc2c5ca6921f1

**Comment by brianking** [comment]
@hector, I need to update deployment instructions and make sure everyone updates their repository. Once I figure it out, I will inform everyone and you can go ahead and delete master.

@berezovskyi Here is our current deployment instructions. 
https://github.com/OSLC/oslc-site-hugo/wiki/Contributing-Setup
What do you mean by auto-deploying? On every commit?

**Comment by brianking** [comment]
@berezovskyi I suggest opening a new issue for auto-deployment, maybe @hectorsanchezmx can look into it.

**Comment by gabrielfdac** [comment]
Unpublished
