### ISSUE TITLE
Simple figures explaining most important steps of how OSLC is used for data integration and data interoperability 

### ISSUE THREAD

**Issue by axelreichwein** [OSLC/oslc-site-hugo#193]
The landing page needs a simple description of how OSLC is used for data integration and data interoperability. This is best done using a simple figure highlighting most important steps.

Section name "How OSLC works"

One subsection on "How OSLC is used for data integration"
A figure below highlighting 3 main steps:

1. Create OSLC REST APIs for different data sources (not necessary if OSLC REST APIs are already available)
2. Define typed links between data from different sources
3. Use mashup applications for search, visualization, analysis, etc.

One subsection on "How OSLC is used for data interoperability"
A figure below highlighting 3 main steps:

1. Create OSLC REST APIs for different data sources (not necessary if OSLC REST API are already available)
2. Make sure that OSLC REST APIs support the same OSLC domain-specific specification like OSLC Requirements Management specification
2. Create client to pull data of OSLC REST API X and push it to OSLC REST API Y

**Comment by billchown** [comment]
I have some diagrams that relate to the way we use OSLC. I'll send them in

**Comment by jamsden** [comment]
Does this still need to be a live blockers?

**Comment by gabrielfdac** [comment]
@jamsden this issue is already done, closing it.
