### ISSUE TITLE
Create archive for the vocabulary pages as well

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/oslc-site-hugo#194]
- [ ] http://open-services.net/wiki/core/CoreVocabulary/

- [ ] http://open-services.net/wiki/architecture-management/OSLC-Architecture-Management-Vocabulary/

- [ ] http://open-services.net/wiki/asset-management/OSLC-Asset-Management-Vocabulary/

- [ ] http://open-services.net/wiki/automation/OSLC-Automation-Vocabulary/

- [ ] http://open-services.net/bin/view/Main/CmVocabulary

- [ ] http://open-services.net/uploads/wiki/perfmon.html

- [ ] http://open-services.net/uploads/wiki/itm-vocabulary.html @jamsden 

- [ ] http://open-services.net/uploads/wiki/reconciliation.html @jamsden is it used anywhere?

- [ ] http://open-services.net/bin/view/Main/RmVocabulary

- [ ] http://open-services.net/bin/view/Main/ScmSpecV1

**Comment by jamsden** [comment]
The IBM Tivoli Monitoring Vocabulary http://open-services.net/uploads/wiki/itm-vocabulary.html is a jazz.net, not open-services.net vocabulary. Looks like the Tivoli team used some open-services.net facilities for developing the vocabulary. Would be nice to archive it, but it does not need to be part of the open-services.net/ns documents.

Reconciliation is a finalized open-services.net 2.0 specification that was not yet included in the OASIS documentation maintenance and migration work. This specification is inactive, but could be added to the OASIS Domains TC at some point in the future. The PDF document has been preserved in the TC documents area. There are draft reconciliation-vocab.html and ttl files in the Domains TC repo, so these could be included in open-services.net/ns.

**Comment by gabrielfdac** [comment]
This issue is already done. See archive.open-services.net
