### ISSUE TITLE
Need a "Standards Corner" to report on spec development news

### ISSUE THREAD

**Issue by jamsden** [OSLC/oslc-site-hugo#196]
Should discuss major updates in the OASIS OSLC standards activities:

- Changes in OASIS TC organizations
- Specification updates: new, modified, migrated
- Published specs especially for public review, Committee Specifications and OASIS Standards.

**Comment by berezovskyi** [comment]
Jim, please go ahead and prepare the content. We will publish it under the News section as regular blog posts and promote it through all the available channels.
