### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#197]
Let's move the analytics code over just before launch. We already have a code AFAIK.

**Comment by berezovskyi** [comment]
@brianking I think most people from our area have a uBlock or something similar and it will block GA code (as least I do :). Maybe we want to configure Nginx to keep the logs and do it the old-school way.

**Comment by brianking** [comment]
We can use both, sure. I highly dispute that "most people" block it.

**Comment by jamsden** [comment]
Was there one for the old site we can reuse? Should be noted in the admin document I sent you for the old site.

**Comment by gabrielfdac** [comment]
I can't find this document, did you send it by email?

**Comment by jamsden** [comment]
From OSLC-accounts-minimal-support2016.docx:

We have the following active @open-services.net mailing accounts:
* stc-private@open-services.net: this account only serves to forward email to the steering committee members. Set up this forwarding under Email Forwarders. Is this still needed? The OASIS OSLC MS StC email is oslc-sc@lists.oasis-open.org
* ask@open-services.net Vanity email that forwards to stc-private@open-services.net, which in turn forwards to the StC members
* webmaster@open-services.net (p/w: VHYaKN3cUFaM9WxWArQqQoVxc) Most “ask the admin” emails go here. You can update its password in the cPanel. I usually checked this once a week or so. This is the account where you’ll get requests to add new software/organizations.

**Comment by brianking** [comment]
@jamsden you just posted a password in a public location.

**Comment by jamsden** [comment]
None of those are valid anymore.
