### ISSUE TITLE
New Homepage Design/Content

### ISSUE THREAD

**Issue by gabrielfdac** [OSLC/oslc-site-hugo#198]
After extensive discussion on issue #188 we've chosen a new direction for the homepage layout and content.

The Design proposal can be found [Here](https://xd.adobe.com/view/a82bb371-9758-4b23-9f24-9993209c5a57/)

And [this](https://docs.google.com/document/d/1yPwTxBXLGximPwzIDAZLqZwr8j-wI8EjRi34ZJxYM4Q/edit#) is document tracking the content changes.

Feedback is needed.

**Comment by jamsden** [comment]
Is this complete enough to close or at least remove the live blocker? Adding content will be ongoing. New issues should be raised for specific proposed content updates.

**Comment by gabrielfdac** [comment]
@jamsden agreed, and it is already finished. Closing
