### ISSUE TITLE
Preservation of the links to the RDF namespaces

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/oslc-site-hugo#2]
Currently, http://open-services.net/ns/core redirects to http://open-services.net/wiki/core/CoreVocabulary/

We should ensure that links do not get broken during the transition.

**Comment by brianking** [comment]
@jamsden is taking the lead on this. We already have a proposed solution in place that involves the content moving to OASIS but namespace urls being preserved by redirects. Jim is consulting the technical group to get buy-in for this.

**Comment by brianking** [comment]
Latest plan:

1. http://open-services.net/specifications - Preserve this page, but this page should be significantly simplified to organize the specs in a simple list by the governing TC. 

2. http://open-services.net/specifications/requirements-management-2.0/ - this (for example) is the landing page for the document's governance page - this should redirect to the OASIS TC that now managing the page - probably the public URI.

3. http://open-services.net/bin/view/Main/RmSpecificationV2 - This is the link to the specification itself which should be redirected to either the migrated OASIS specification, or the PDF document in the TC's Documents folder, e.g., https://www.oasis-open.org/committees/document.php?document_id=61070&wg_abbrev=oslc-domains

Rainer thinks it would be a good idea to keep also a landing page for the next level e.g.:
http://open-services.net/specifications/requirements-management-2.0/
"Those pages should also be simplified and mostly point to the locations at the OASIS TC’s
Alternatively, if a good landing page already exists at the OASIS TC, the URI could be a direct redirect to that location."

**Comment by brianking** [comment]
I just checked in the namespace RDF files to ns/.

* See commit 7247cd0
* Files: https://github.com/OSLC/oslc-site-hugo/tree/master/content/ns

It's live at test site http://oslc.co to have a look.

I'll need help with the rewrite rules:
https://github.com/OSLC/oslc-site-hugo/blob/master/content/ns/.htaccess

What else needs to be done here @jamsden @berezovskyi ?

**Comment by jamsden** [comment]
The old vocabulary RDF pages have been preserved in https://github.com/oasis-tcs/oslc-domains/tree/master/open-services-vocabs. We need these in OASIS as the reference documents that are being migrated - same as the specs. You could redirect there, but its probably better to redirect to your copy as this will be faster and will provide a buffer from what is published in OASIS and what is published here. We need to be careful to keep these in good synchronization though.

**Comment by brianking** [comment]
@jamsden Have the files you put at https://github.com/oasis-tcs/oslc-domains/tree/master/open-services-vocabs been updated recently, or are they the same as what is on open-services.net?

**Comment by jamsden** [comment]
Its a mixture since the specs are all in transition. The specs are in three states:
OASIS Committee Specification - OSLC Core 3.0 - I used its vocabulary and HTML files as published on the OASIS doc library
OASIS Committee Specification Drafts or Working Drafts - I used these for all the vocabulary and shape HTML files because we don’t have any other way of generating them
Old open-services.net/ns <http://open-services.net/ns> vocabulary RDF files - I used these for all the vocabulary RDF files except for OSLC Core 3.0 and CM 3.0 where I used the ones published on OASIS.

**Comment by berezovskyi** [comment]
I don't think my message came across from the SEO standpoint. Here is the SERP (SEO buzzword for _search engine result page_) for "oslc core":

<img width="661" alt="image" src="https://user-images.githubusercontent.com/64734/32492384-604acaaa-c3ba-11e7-82d7-46373f64f2ac.png">

The new site should redirect all requests via `.htaccess` from this URI

http://open-services.net/bin/view/Main/OslcCoreSpecification

to this URI

http://oslc.co/specifications/archive/core-2.0/ (see #181)

@jamsden @rersch if people will open the former URL (and they will as the Google will still point to it for a while), they will get a 404 (a beautiful one, eg https://oslc.github.io/jinkies, but still a 404). I think I am repeating it here a thousand times but a community website should not care about the Core TC archival needs. If Core TC insists, all archived specs can refer to the PDF as the authoritative source but the content should remain accessible in HTML over existing links to the wider community.

**Comment by brianking** [comment]
There is an open issue for setting up redirects at #169

**Comment by gabrielfdac** [comment]
Is this still needed?

**Comment by gabrielfdac** [comment]
Redundant, latest discussions in #16 closing
