### ISSUE TITLE
About - People Content

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#20]
Mainly about the Steering Committee.

We can harvest parts from:
https://open-services.net/tagged/governance/

Open question:
Do we want to talk much about the history of the community?

**Comment by jamsden** [comment]
This content can be ignored. All you need to do is add a statement in the About page indicating all the OSLC specifications are managed by the OASIS governance process and link to the OSLC Member Section public page: https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=oslc-ms

**Comment by brianking** [comment]
@jamsden I was thinking more about taking some of the content from http://open-services.net//pub/Main/CommunityGovernanceUpdatesDrafts/OSLC-Governance-Update-slides-2012-May-08.pdf and adapting it. But since some of the model is going away, i.e. membership, then yes perhaps this page is not necessary. However, the page you link to at OASIS does not give much information, so I feel we need some sort of overview of what the community looks like.

What it could be is more related to the whole OSLC ecosystem. See the chart in this post, for example:

http://open-services.net/blog/all-systems-go-for-oslc-at-oasis/

What Rainer, Andreas, and I talked about recently was the 'ecosystem'. I started a presentation based on some slides that Rainer, had. It still needs to be adapted/updated:

https://docs.google.com/presentation/d/1_CVGDS_gngN79hl1Gra-MfNGkwZQiVAFjmGxoTGC1H8/edit?usp=sharing

Perhaps this page should therefore be more focused on that.

Adding @rersie for input.

**Comment by jamsden** [comment]
Doesn't need to be a live blockers, unless someone's legal department complains. Whose handling this?

**Comment by gabrielfdac** [comment]
@jamsden at this time, no one. Who should be assigned to it?

**Comment by gabrielfdac** [comment]
I'll remove the label for now

**Comment by berezovskyi** [comment]
There is some people section for the SC committee now. Shall we keep it, @jamsden? https://open-services.net/about/#people

**Comment by rersch** [comment]
I would recommend keeping the steering committee information as is on open-services.net, but add the link Jim provided for more details (bio’s).
It’s a nicer overview and fits to the layout of the other pages.

**Comment by gabrielfdac** [comment]
So we'll keep the steering committee section in about, but bellow it add a link to https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=oslc-sc, correct?

**Comment by berezovskyi** [comment]
The PGB and TSC members are listed correctly under https://open-services.net/about/
