### ISSUE TITLE
Hang on Page Loads

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#200]
For the last while (roughly 10-14 days, I can't say precisely) when site pages load in Firefox, they is a hang of a couple of seconds before the page fully loads. The browser "spinner" appears. 

It appears that it is waiting for something to load, perhaps a script.

If you need me to do more debugging, let me know.

**Comment by gabrielfdac** [comment]
This is not exclusive to Firefox, it's happening to me also on Chrome.

**Comment by jailandrade** [comment]
There were a bunch of links in the <head> that block the load at start, I solved partially this with https://github.com/OSLC/oslc-site-hugo/commit/bcb2c06a3a615fbd912e043dc78b5d28bba84f30

**Comment by gabrielfdac** [comment]
This has been fixed. Closing

**Comment by brianking** [comment]
Nice, it is super snappy now!
