### ISSUE TITLE
Image for landing page

### ISSUE THREAD

**Issue by axelreichwein** [OSLC/oslc-site-hugo#201]
A picture showing that data from different engineering disciplines (e.g. ALM, PLM, IoT, requirements, system architecture, 3D model, simulation model, software) can be linked as in the attached image from https://data.world/ would explain very quickly what the objective/potential of OSLC is.
![connecteverything](https://user-images.githubusercontent.com/3833852/32914725-6f079434-cacb-11e7-8bb0-150d3c857500.PNG)

**Comment by gabrielfdac** [comment]
I think this conflicts with the new approach of the homepage, with is to include highlight the OSLC benefits without overwhelming new comers. 

Should this perhaps have this on another page? (Maybe the one we'll have for the benefits?) Or where would you see that image go? Considering we'll have -
 Benefits > Getting Started > Supporters - as sections.

My concern with adding more section like this is:

- With the new approach this would be bellow other sections which have higher priority than this thus making it something most visitors won't see;
- As we start adding more of these we'll have too much content there. Confusing the visitor where to find information or where to find what he(she) needs.

**Comment by axelreichwein** [comment]
I had in mind for the image to be at the very top, for example overlaying the current image with the dots.
