### ISSUE TITLE
Change the behavior of the category selector on the news page

### ISSUE THREAD

**Issue by jailandrade** [OSLC/oslc-site-hugo#203]
Right now we are using duplicate posts to be able to show posts in the news subpages, we decided to use the same filter of the resource page to replace the functionality and avoid duplicate posts.

**Comment by brianking** [comment]
Happy to see this happening. Makes it easier to deploy new categories, and less overhead when creating new blog posts. 

Please consider updating the blog post instructions with more information on categories:
https://github.com/OSLC/oslc-site-hugo/wiki/Creating-A-News-Post

**Comment by gabrielfdac** [comment]
@brianking yes, we will update the documentation in due time. For now we're trying to make a push for launching the website live, so it might come after that.

**Comment by gabrielfdac** [comment]
This solution has been implemented, merged and deployed. Closing.
