### ISSUE TITLE
Letsencrypt TLS/SSL cert for discourse.oslc.co

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/oslc-site-hugo#212]
I started to link to some posts on that forum externally (just a test of engagement in a letter to lyo-dev), but it would be good to get TLS going, so that both the login page is secure and the links are stable.

On the different note, do we plan to remain on the oslc.co or do you plan to kill that domain and use open-services.net instead? Because then we can't really link to discourse.oslc.co then

**Comment by berezovskyi** [comment]
@brianking mentioned a while ago in #68 that @hectorsanchezmx had Letsencrypt ready but, as I understood, for the open-services.net domain, not for oslc.co.

**Comment by gabrielfdac** [comment]
@berezovskyi I do not have any details on that Letsencrypt, I'll see if I can find anything on that. And as far as I understood the idea was to use open-services.net, I could be wrong though.

**Comment by berezovskyi** [comment]
I think TLS is a live blocker given that https://security.googleblog.com/2018/02/a-secure-web-is-here-to-stay.html

**Comment by berezovskyi** [comment]
![image](https://user-images.githubusercontent.com/64734/47182496-e1c78480-d325-11e8-96b9-ca6ee25719a6.png)

**Comment by berezovskyi** [comment]
Forum post preview is not working as a result of that.

**Comment by berezovskyi** [comment]
@FabioRNT moved to the new domain and fixed the issue
