### ISSUE TITLE
Distorted logo sizes

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/oslc-site-hugo#215]
![image](https://user-images.githubusercontent.com/64734/46821372-be7e6180-cd88-11e8-9799-931926b8d766.png)

looks really wierd. can we crop or have white space around logos instead of changing their proportions? many oompanies forbid changing aspect ratios (I am certainly not impressed with Lyo logo)

**Comment by gabrielfdac** [comment]
Hi Andrew,

This is an issue with Mozilla, no proportions were changed just how the browser interprets the styling. I'll issue a fix when I can, thanks for noticing!

**Comment by gabrielfdac** [comment]
@berezovskyi just pushed a fix for that. Should work normally on Mozilla now. I'll close as soon as you confirm the fix on your end as well.

PS: You'll need a cleared cache to see the changes, you can use ctrl (or command) + F5 to clear the cache of the page you're trying to load.

**Comment by berezovskyi** [comment]
perfect, thank you!
