### ISSUE TITLE
Log the referer headers

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/oslc-site-hugo#216]
We should make sure that the links to the temp oslc.co site and the old open-services.net documents are updated wherever possible.

Let's gather the referer header on the:

* access log entries to the oslc.co site
* error log entries to the open-services.net site

**Comment by FabioRNT** [comment]
Just configured oslc.co to redirect to open-services.net. Also configured access logs for oslc.co and open-services.org and error log for open-services.net

**Comment by berezovskyi** [comment]
Cool, thank you! Does it include the referrer headers?

/Andrew



On Sun, Oct 28, 2018 at 12:37 AM +0200, "Fábio Ribeiro de Assis Neto" <notifications@github.com<mailto:notifications@github.com>> wrote:


Just configured oslc.co to redirect to open-services.net. Also configured access logs for oslc.co and open-services.org and error log for open-services.net

**Comment by jamsden** [comment]
Awesome, looks great. Thanks.


Jim Amsden, Senior Technical Staff Member
OSLC and Linked Lifecycle Data
919-525-6575

**Comment by FabioRNT** [comment]
Configured `oslc.co` and `open-services.org` to log the Accept header. @berezovskyi is there other headers that should be logged?

**Comment by berezovskyi** [comment]
Did you mean the Referer header?

**Comment by berezovskyi** [comment]
Thanks. Works perfectly. For the last two days, oslc.co was only accessed by the bots. Everyone else got the idea about the permanent redirect by now.
