### ISSUE TITLE
Change the YT channel name

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/oslc-site-hugo#218]
We should remove the .NET part.

https://www.youtube.com/channel/UCO09R3FGcxbMudDIc3htdKQ

**Comment by gabrielfdac** [comment]
Should we change it to the full name? Or perhaps simply OSLC?

Or Open Services is fine?

**Comment by gabrielfdac** [comment]
Channel name changed to **Open Services for Lifecycle Collaboration**
