### ISSUE TITLE
Missing information about User Groups on new open-services.net

### ISSUE THREAD

**Issue by rersch** [OSLC/oslc-site-hugo#220]
We have at least one active User Group (Integration Patterns) and we should promote the instrument User Groups very prominent on open-services.net for additional topics.
At minimum User Groups should have their own overview page, maybe with a link from the “Working Groups” page or with an own entry in the menubar.

**Comment by gabrielfdac** [comment]
How about we simply list that within the **Working Groups** page?

**Comment by berezovskyi** [comment]
We don't need any strict WG or UGs under Open Project. If there is such a need, please reopen when the user group gains activity and wishes to be promoted on the website.
