### ISSUE TITLE
Specification link redirects not working?

### ISSUE THREAD

**Issue by jamsden** [OSLC/oslc-site-hugo#222]
Shouldn't http://open-services.net/bin/view/Main/QmSpecificationV2 redirect to http://archive.open-services.net/bin/view/Main/QmSpecificationV2

**Comment by berezovskyi** [comment]
It does. You just have to click on the Archive link because the redirection is not automatic.

**Comment by gabrielfdac** [comment]
If that is an important link or often used one we could create a permanent redirect on nginx

**Comment by berezovskyi** [comment]
Is it a duplicate of #225?

**Comment by berezovskyi** [comment]
The redirect works now
