### ISSUE TITLE
Mobile navbar has extra top margin

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/oslc-site-hugo#224]
![image](https://user-images.githubusercontent.com/64734/48281729-c567c500-e457-11e8-9bfd-16dfba279c30.png)

**Comment by gabrielfdac** [comment]
Good catch, just added a fix. Let me know if it fixes it for you

**Comment by berezovskyi** [comment]
It does, thank you!

--
/Andrew

On 2018-11-13 , at 22:18, Gabriel Fernandes de Araujo Costa <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #224<https://github.com/OSLC/oslc-site-hugo/issues/224>.
