### ISSUE TITLE
Setup redirects for old OSLC specification wikis

### ISSUE THREAD

**Issue by jamsden** [OSLC/oslc-site-hugo#225]
Many people have saved links to the old open-services.net specification wikis, and they are surprised when these links return 404. There is a button on the error page that takes the user to corresponding page in the archive. However, each of the specifications should have direct redirects to the specification wikis. For example, the OSLC Core 2.0 specification should redirect https://open-services.net/specifications/core-2.0/index.html to https://archive.open-services.net/specifications/core-2.0/index.html.

**Comment by jamsden** [comment]
| Domain | Specification
-- | -- | --
Core | https://archive.open-services.net/specifications/core-2.0/index.html | https://archive.open-services.net/bin/view/Main/OslcCoreSpecification.html
Resource Shape | https://archive.open-services.net/specifications/resource-shapes-2.0/index.html |  
OSLC Query |   |  
Tracked Resource Set | https://archive.open-services.net/specifications/tracked-resource-set-2.0/index.html | https://archive.open-services.net/wiki/core/TrackedResourceSet-2.0/index.html
Configuration Management | https://archive.open-services.net/specifications/configuration-management/index.html |  
Requirements Management | https://archive.open-services.net/specifications/requirements-management-2.0/index.html | https://archive.open-services.net/bin/view/Main/RmSpecificationV2.html
Change Management | https://archive.open-services.net/specifications/change-management-2.0/index.html | https://archive.open-services.net/bin/view/Main/CmSpecificationV2.html
Quality Management | https://archive.open-services.net/specifications/quality-management-2.0/index.html | https://archive.open-services.net/wiki/quality-management/index.html
Architecture Management | https://archive.open-services.net/specifications/architecture-management-2.0/index.html | https://archive.open-services.net/wiki/architecture-management/OSLC-Architecture-Management-Specification-Version-2.0/index.html
Asset Management | https://archive.open-services.net/specifications/asset-management-2.0/index.html | https://archive.open-services.net/wiki/asset-management/OSLC-Asset-Management-2.0-Specification/index.html
Automation | https://archive.open-services.net/specifications/automation-2.0/index.html | https://archive.open-services.net/wiki/automation/OSLC-Automation-Specification-Version-2.0/index.html
Performance Modeling | https://archive.open-services.net/specifications/performance-monitoring-2.0/index.html | https://archive.open-services.net/wiki/performance-monitoring/OSLC-Performance-Monitoring-Specification-Version-2.0/index.html
Estimation and Measurement | https://archive.open-services.net/specifications/estimation-and-measurement-20/index.html | https://archive.open-services.net/wiki/estimation-and-measurement/Estimation-and-Measurement-Service-Version-1.0_-REST-API/index.html
Reconciliation | https://archive.open-services.net/specifications/reconciliation-2.0/index.html | https://archive.open-services.net/wiki/reconciliation/OSLC-Reconciliation-Specification-Version-2.0/index.html

**Comment by FabioRNT** [comment]
>  	Domain	Specification
> Core	https://archive.open-services.net/specifications/core-2.0/index.html	https://archive.open-services.net/bin/view/Main/OslcCoreSpecification.html
> Resource Shape	https://archive.open-services.net/specifications/resource-shapes-2.0/index.html	 
> OSLC Query	 	 
> Tracked Resource Set	https://archive.open-services.net/specifications/tracked-resource-set-2.0/index.html	https://archive.open-services.net/wiki/core/TrackedResourceSet-2.0/index.html
> Configuration Management	https://archive.open-services.net/specifications/configuration-management/index.html	 
> Requirements Management	https://archive.open-services.net/specifications/requirements-management-2.0/index.html	https://archive.open-services.net/bin/view/Main/RmSpecificationV2.html
> Change Management	https://archive.open-services.net/specifications/change-management-2.0/index.html	https://archive.open-services.net/bin/view/Main/CmSpecificationV2.html
> Quality Management	https://archive.open-services.net/specifications/quality-management-2.0/index.html	https://archive.open-services.net/wiki/quality-management/index.html
> Architecture Management	https://archive.open-services.net/specifications/architecture-management-2.0/index.html	https://archive.open-services.net/wiki/architecture-management/OSLC-Architecture-Management-Specification-Version-2.0/index.html
> Asset Management	https://archive.open-services.net/specifications/asset-management-2.0/index.html	https://archive.open-services.net/wiki/asset-management/OSLC-Asset-Management-2.0-Specification/index.html
> Automation	https://archive.open-services.net/specifications/automation-2.0/index.html	https://archive.open-services.net/wiki/automation/OSLC-Automation-Specification-Version-2.0/index.html
> Performance Modeling	https://archive.open-services.net/specifications/performance-monitoring-2.0/index.html	https://archive.open-services.net/wiki/performance-monitoring/OSLC-Performance-Monitoring-Specification-Version-2.0/index.html
> Estimation and Measurement	https://archive.open-services.net/specifications/estimation-and-measurement-20/index.html	https://archive.open-services.net/wiki/estimation-and-measurement/Estimation-and-Measurement-Service-Version-1.0_-REST-API/index.html
> Reconciliation	https://archive.open-services.net/specifications/reconciliation-2.0/index.html	https://archive.open-services.net/wiki/reconciliation/OSLC-Reconciliation-Specification-Version-2.0/index.html

Just created and tested the redirects mentioned in this table, can anyone test it to see if everything is  correct?

**Comment by jamsden** [comment]
For QM spec: https://open-services.net/wiki/quality-management/index.html should have been  https://archive.open-services.net/bin/view/Main/QmSpecificationV2.html 

All others were verified as correct.

**Comment by FabioRNT** [comment]
> For QM spec: https://open-services.net/wiki/quality-management/index.html should have been https://archive.open-services.net/bin/view/Main/QmSpecificationV2.html
> 
> All others were verified as correct.

Just fixed it.

**Comment by berezovskyi** [comment]
@jamsden, @ndjc: so, I have slept on this and thought about a multitude of versions of the spec and how we consider them "complete", "authoritative", "obsolete" etc. So, I have switched from a table to a simple list with all the links present. See a side-by-side comparison:

![image](https://user-images.githubusercontent.com/64734/58080996-89ef4580-7bb4-11e9-984f-00d8b619dd58.png)

We have a few more options: remove the "Governing TC" column and stack the links in the Status column (while renaming it to Editions, for example, and removing a link from the title). Also, we can use a dropdown instead of linked labels but that will prevent us from color-coding them.

I was thinking to use them in the following way:

- green for current finalised specs
- blue for reviewed drafts
- orange for Final specs
- light blue for drafts
- grey for obsolete specs

https://getbootstrap.com/docs/3.4/components/#available-variations

**Comment by berezovskyi** [comment]
And ofc we can show a tooltip for people who are not fluent in abbrspeak:

<img width="1440" alt="Skärmavbild 2019-05-21 kl  03 08 49" src="https://user-images.githubusercontent.com/64734/58081632-ae97ed00-7bb5-11e9-8e87-bba2be690ea6.png">

And this is how a dropdown can look like (did not have time to fix the styles but hope @gabrielfdac can help me out later):

![image](https://user-images.githubusercontent.com/64734/58082434-42b68400-7bb7-11e9-80b2-57e0a28bb034.png)

**Comment by berezovskyi** [comment]
Work is taking place in https://github.com/OSLC/oslc-site-hugo/pull/244

**Comment by jamsden** [comment]
I'm thinking about how this will scale. We will be publishing a lot of revisions of documents, project WD as needed to make the documents visible, PSPRD for public review, PS with various revisions. OASIS project standards, etc. Not all of these will need to be linked to open-services.net as many represent specification lifecycle artifacts rather than published standards. 

Documents can be in three places:
1. oslc-op GitHub - these are specifications under development, specific versions might be tagged, but these will be changing. This is primarily for the PGB and TSC, or anyone contributing to oslc-op
2. Where OASIS publishes project specification standards track documents for managing specification lifecycle. This is primarily for the OASIS community for reviewing and managing standards track documents.
3. open-services.net - where developers building client and server applications go to access OSLC related materials.

So I think we should only publish two versions on open-services.net - the finalized 2.x versions that are in common use today, and the latest published OASIS document, regardless of specification status (its noted in the document). 

Older versions can be accessed through the archive, OASIS documents or GitHub as needed. 

The Domains specifications are a bit different as they are suppose to be the 2.x specifications in the OASIS format. Its not clear we need to publish two versions of these.

Let's discuss.

**Comment by berezovskyi** [comment]
> Documents can be in three places

I don't think I fully agree with the dichotomy. I think open-services should be a landing place for all people: developers, folks who want to read/review specs and the developers. I honestly don't think the larger OASIS community cares about our specs (other than asking why do we need OSLC) unless we actively engage them.

The generation of the HTML code can be automated through some JSON data and templating. @gabrielfdac should be able to help with that. I think we are not publishing that "lot" that we can't add a link to every major revision of the spec (every CSPRD and higher).

Github tags is the last place we should be forcing people to go through. Moreover, nobody has ever done this before here (as opposed to us tagging releases in Eclipse Lyo) and I don't see a reason to believe some discipline will magically emerge out of nothing. I don't think that adding a link should be that harder than git tagging the repo & making an email/forum announcement.

Just to be clear, my proposal is just to LINK to the documents on open-services. There will be no documents published there. Everything will be hosted in the archive, OASIS, or Github (through GitHack).

> we should only publish two versions on open-services.net
>
> Older versions can be accessed through the archive, OASIS documents or GitHub as needed.

All versions will be accessed through the resource where they were originally published. Nothing will be published on open-services.net.

**Comment by jamsden** [comment]
OSLC specification development can generate a lot of "noise" that is not interesting to people building OSLC client and server apps. This is the reason for separating the specification development vs. specification use concerns. 

OASIS will be actually publishing a rendered copy of the specs. The process for doing that is something we need to discuss soon.

**Comment by berezovskyi** [comment]
Yes and we can link to those specs. We don't have to announce every link update and save some noise.

--
/Andrew
(from phone)



On Tue, May 21, 2019 at 5:22 PM +0200, "Jim Amsden" <notifications@github.com<mailto:notifications@github.com>> wrote:


OSLC specification development can generate a lot of "noise" that is not interesting to people building OSLC client and server apps. This is the reason for separating the specification development vs. specification use concerns.

OASIS will be actually publishing a rendered copy of the specs. The process for doing that is something we need to discuss soon.

**Comment by berezovskyi** [comment]
A list of old spec links from @DavidJHoney:

All the specs under https://tools.oasis-open.org/version-control/browse/wsvn/oslc-core/trunk/specs/#_trunk_specs_: 
https://tools.oasis-open.org/version-control/browse/wsvn/oslc-core/trunk/specs/config/config-resources.html 
https://tools.oasis-open.org/version-control/browse/wsvn/oslc-core/trunk/specs/config/config-vocab.html 
https://tools.oasis-open.org/version-control/browse/wsvn/oslc-core/trunk/specs/config/oslc-config-mgt.html 
https://tools.oasis-open.org/version-control/browse/wsvn/oslc-core/trunk/specs/config/versioned-resources.html 
https://tools.oasis-open.org/version-control/browse/wsvn/oslc-core/trunk/specs/trs/tracked-resource-set-vocab.html 
https://tools.oasis-open.org/version-control/browse/wsvn/oslc-core/trunk/specs/trs/tracked-resource-set.html 
https://tools.oasis-open.org/version-control/browse/wsvn/oslc-core/trunk/specs/actions.html 
https://tools.oasis-open.org/version-control/browse/wsvn/oslc-core/trunk/specs/attachments.html 
https://tools.oasis-open.org/version-control/browse/wsvn/oslc-core/trunk/specs/core-vocab.html 
https://tools.oasis-open.org/version-control/browse/wsvn/oslc-core/trunk/specs/dialogs.html 
https://tools.oasis-open.org/version-control/browse/wsvn/oslc-core/trunk/specs/discovery.html 
https://tools.oasis-open.org/version-control/browse/wsvn/oslc-core/trunk/specs/oslc-core-overview-v3.html 
https://tools.oasis-open.org/version-control/browse/wsvn/oslc-core/trunk/specs/oslc-core.html 
https://tools.oasis-open.org/version-control/browse/wsvn/oslc-core/trunk/specs/oslc-query.html 
https://tools.oasis-open.org/version-control/browse/wsvn/oslc-core/trunk/specs/resource-preview.html 
https://tools.oasis-open.org/version-control/browse/wsvn/oslc-core/trunk/specs/resource-shape.html 

> I think the spec drafts in trunk don't have much value but shall link to the new drafts here on the 'master' branch.

Specs under https://tools.oasis-open.org/version-control/browse/wsvn/oslc-ccm/tags/final/specs/#_tags_final_specs_: 

- [ ] https://tools.oasis-open.org/version-control/browse/wsvn/oslc-ccm/tags/final/specs/change-mgt/change-mgt-actions.html 
- [ ] https://tools.oasis-open.org/version-control/browse/wsvn/oslc-ccm/tags/final/specs/change-mgt/change-mgt-resources.html 
- [ ] https://tools.oasis-open.org/version-control/browse/wsvn/oslc-ccm/tags/final/specs/change-mgt/change-mgt.html 
- [ ] https://tools.oasis-open.org/version-control/browse/wsvn/oslc-ccm/tags/final/specs/config-mgt/config-resources.html 
- [ ] https://tools.oasis-open.org/version-control/browse/wsvn/oslc-ccm/tags/final/specs/config-mgt/config-vocab.html 
- [ ] https://tools.oasis-open.org/version-control/browse/wsvn/oslc-ccm/tags/final/specs/config-mgt/oslc-config-mgt.html 
- [ ] https://tools.oasis-open.org/version-control/browse/wsvn/oslc-ccm/tags/final/specs/config-mgt/versioned-resources.html 

Older specs under https://open-services.net/specifications/

- [ ] List

Older specs (links now broken) 

- [ ] https://open-services.net/wiki/core/TrackedResourceSet-2.0/ 
- [ ] https://open-services.net/wiki/core/Vocabulary-Annotation-Vocabulary/ 
- [ ] https://open-services.net/wiki/reconciliation/OSLC-Reconciliation-Specification-Version-2.0 
- [ ] https://open-services.net/bin/view/Main/CmSpecificationV2#CM_Resource_Definitions 
- [ ] https://open-services.net/bin/view/Main/QmSpecificationV2#QM_Resource_Definitions 
- [ ] https://open-services.net/bin/view/Main/AmSpecV2#AM_Resource_Definitions 
- [ ] https://open-services.net/bin/view/Main/RmSpecificationV2#RM_Resource_Definitions 
- [ ] https://open-services.net/bin/view/Main/AssetMgSpecificationV2 

Broken links found by Google: 

- [ ] https://open-services.net/wiki/architecture-management/OSLC-Architecture-Management-Specification-Version-3.0/ 
- [ ] https://open-services.net/wiki/asset-management/OSLC-Asset-Management-2.0-Specification/ 

Other links found by Google: 
http://docs.oasis-open.org/oslc-domains/oslc-am/v2.1/oslc-am-v2.1-part1-architecture-management-spec.html 

Broken links in https://www.w3.org/Submission/shapes/#OSLC: 

- [ ] http://open-services.net/bin/view/Main/OslcCoreSpecification

**Comment by berezovskyi** [comment]
cc @jamsden and @ndjc we might as well deal with these too

@DavidJHoney @jamsden what does the tag `final` mean in the links above?

**Comment by berezovskyi** [comment]
Please see https://open-services.net/specifications/

NB! More links on https://archive.open-services.net/specifications/index.html and https://docs.oasis-open.org/

**Comment by berezovskyi** [comment]
due to oslc-op/oslc-specs#65 I have escalated the priority for this and added a pair of redirects for both wikis

**Comment by berezovskyi** [comment]
@DavidJHoney all of your links now resolve except for https://archive.open-services.net/bin/view/Main/AmSpecV2#AM_Resource_Definitions which redirects to a 404 wiki page redirecting visitors to https://archive.open-services.net/wiki/architecture-management/OSLC-Architecture-Management-Specification-Version-2.0/index.html. I will try to set up a redirect for this that would not cause a 404.

**Comment by berezovskyi** [comment]
https://open-services.net/bin/view/Main/AmSpecV2#AM_Resource_Definitions now redirects directly to  https://archive.open-services.net/wiki/architecture-management/OSLC-Architecture-Management-Specification-Version-2.0/index.html#AM_Resource_Definitions but https://archive.open-services.net/bin/view/Main/AmSpecV2#AM_Resource_Definitions won't redirect you manually.

Please reopen if I missed something.

**Comment by DavidJHoney** [comment]
Re: what does the tag final mean in the links above?
I don't know. I just copied the URIs from FF bookmarks or other pages that referenced them.
