### ISSUE TITLE
oslc.co Domain Changes

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#24]
The following needs to be done:

* [x] Change nameservers to point to Digital Ocean
* [x] Change redirect to go to https://oslc.github.io
* [ ] Setup basic index page on droplet, and when delete the redirect so that it resolves to this page
* [x] Move domain to new registrar. It expires in 36 days and costs $30. We may be able to get cheaper somewhere else

**Comment by berezovskyi** [comment]
* For now there is a Discourse welcome page there.
* HTTPS is not working any more (connection refused).
* my favourite registrar name.com charges this:
    * Registration: $6.99/yr
    * Renewal: $28.00/yr
    * Transfer: $22.99/yr

**Comment by brianking** [comment]
* The Discourse login page is there now, because I have setup discourse. However, the correct home for Discourse is http://discourse.oslc.co/. I will look into putting a simple welcome page at oslc.co.
* I will look into activating https.
* Yesterday I transferred the domain to namecheap.com for the registrar, at a cost of $22.99/yr. The change is propagating, the status currently at "pendingTransfer".

**Comment by brianking** [comment]
The domain transfer to namecheap.com is complete.

**Comment by berezovskyi** [comment]
I belive this one is done and the rest follows in #68
