### ISSUE TITLE
TRS NS uris are broken

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/oslc-site-hugo#242]
https://open-services.net/ns/core/trs#ChangeLog is not available

This may be a variation of #238 or simply not implemented yet given that the TRS spec has not been finalised.

**Comment by berezovskyi** [comment]
@jamsden @ndjc what's your opinion about fixing this?

@gabrielfdac @FabioRNT do you know why is this request failing? And why I don't get the 404 page in the browser?

**Comment by berezovskyi** [comment]
ping

**Comment by jamsden** [comment]
We havn't published the trs vocabulary or shapes yet.

**Comment by berezovskyi** [comment]
That is incorrect unless I am missing something. TRS 2.0 was finalised? Then we must publish the 2.0 vocab and shapes...

--
/Andrew
(from phone)



On Thu, Jun 27, 2019 at 9:38 PM +0200, "Jim Amsden" <notifications@github.com<mailto:notifications@github.com>> wrote:


We havn't published the trs vocabulary or shapes yet.

**Comment by jamsden** [comment]
As far as I know, the TRS vocabulary was never published to open-services.net. Its not listed in https://archive.open-services.net/wiki/core/Vocabulary-index/index.html and I didn't collect one in https://github.com/oasis-tcs/oslc-domains/tree/master/open-services-vocabs

**Comment by berezovskyi** [comment]
Okay, I indeed found no OSLC StC WG approval, but then we need to change the status of TRS 2.0 from Final to Draft on https://open-services.net/specifications/ because it was never finalised? But then, we should be allow to break compat on TRS spec but then in reality it is used in production, right?

**Comment by berezovskyi** [comment]
I have updated the TRS 2.0 spec link to say that the version on the archive was never Final: https://open-services.net/specifications/

**Comment by jamsden** [comment]
I'm reluctant to change anything in those 2.0 specifications, or anything in the archive for that matter. We don't understand the history of TRS. Its likely the spec got done, the implementations were completed, and there was just no one to get the vocabulary published. Nick might know.

**Comment by jamsden** [comment]
The fact that you didn't find the approval doesn't mean there wasn't one. It might be in the mailing list, archive, that's were I found them for Automation.

**Comment by ndjc** [comment]
As far as I can see the TRS 2.0 spec never quite made it to final status - it was left at 'finalizing', which is the term we used for 'all the expected content is there, we are just making editorial changes and clarifications in response to comments on the draft'.
I do not understand why the vocabularies were not published - they should have been. This was probably just an error.

**Comment by ndjc** [comment]
btw, I will not be doing any updates to TRS before my vacation (July 4-15).

**Comment by berezovskyi** [comment]
The wiki says Finalising Draft and I looked through the SC list. Please update back if you find the approval.

--
/Andrew
(from phone)



On Fri, Jun 28, 2019 at 5:54 PM +0200, "Jim Amsden" <notifications@github.com<mailto:notifications@github.com>> wrote:


The fact that you didn't find the approval doesn't mean there wasn't one. It might be in the mailing list, archive, that's were I found them for Automation.

**Comment by berezovskyi** [comment]
I think it is correct that they were waiting for the SC approval before publishing the vocabs. The question is: what do we do now with that?

--
/Andrew
(from phone)



On Fri, Jun 28, 2019 at 7:03 PM +0200, "Nick Crossley" <notifications@github.com<mailto:notifications@github.com>> wrote:


As far as I can see the TRS 2.0 spec never quite made it to final status - it was left at 'finalizing', which is the term we used for 'all the expected content is there, we are just making editorial changes and clarifications in response to comments on the draft'.
I do not understand why the vocabularies were not published - they should have been. This was probably just an error.

**Comment by berezovskyi** [comment]
Thanks Nick and enjoy your super well deserved break!

--
/Andrew
(from phone)



On Fri, Jun 28, 2019 at 7:04 PM +0200, "Nick Crossley" <notifications@github.com<mailto:notifications@github.com>> wrote:


btw, I will not be doing any updates to TRS before my vacation (July 4-15).
