### ISSUE TITLE
I'm missing my old OSLC-primer

### ISSUE THREAD

**Issue by jadelkhoury** [OSLC/oslc-site-hugo#246]
It's a pity the old oslc-primer (now under archive https://archive.open-services.net/resources/tutorials/oslc-primer/index.html) is not available under https://open-services.net/resources/index.html

Any reason we are not sharing this content?

**Comment by berezovskyi** [comment]
No reason other than it's a multi-page tutorial and would take resources to convert. Let's work on it in https://hackmd.io/OV3pS4kjSH2nfi2ogdIt8A

**Comment by berezovskyi** [comment]
@axelreichwein would be good to get your fresh input as we revive this tutorial.

**Comment by berezovskyi** [comment]
Done. All of the content is now on HackMD. Please go over it and make changes and then I can add a PR with the Tutorial resource for it.

**Comment by berezovskyi** [comment]
Nice preview format with the TOC: https://hackmd.io/OV3pS4kjSH2nfi2ogdIt8A?view

**Comment by berezovskyi** [comment]
Thanks Jim. @jadelkhoury we can publish it tonight.

**Comment by jadelkhoury** [comment]
Agree with @jamsden. Thanks for the effort @berezovskyi.

I'm not familiar with the open-services site. If you show me, I'd be glad to fix. (I wanted to also fix some points to DevleoperGuide in near future too.)

**Comment by berezovskyi** [comment]
Published on https://open-services.net/resources/oslc-primer/. Please re-open if more fixes are necessary.
