### ISSUE TITLE
Update link to Eclipse Lyo from https://open-services.net/resources/index.html

### ISSUE THREAD

**Issue by jadelkhoury** [OSLC/oslc-site-hugo#247]
Eclipse Lyo (the very first entry under resources) point to a very poor page https://open-services.net/resources/tool-20111111/

Suggest we make it point to http://oslc.github.io/developing-oslc-applications/eclipse_lyo/eclipse-lyo.html

**Comment by berezovskyi** [comment]
Could you please update it? I wanted to update the link but then everything seemed wrong to me on that page: https://github.com/OSLC/oslc-site-hugo/edit/master/content/resources/tool-20111111.md

Feel free to push straight to master. The updates will not show up until I deploy manually. Ping me on Slack for that.

**Comment by jadelkhoury** [comment]
I change the content of the file tool-20111111.md now.
I would like to change the filename (hence url) to be less obscure, but don't really know how this site work.

Otherwise, all yours @berezovskyi !

**Comment by jadelkhoury** [comment]
@berezovskyi we continue the discussion on this proper thread.
Are we done? Shall I close this issue then?

**Comment by berezovskyi** [comment]
fixed in https://github.com/OSLC/oslc-site-hugo/commit/2404131b234ac3be160160144e8cf20061a3d66b
