### ISSUE TITLE
Is there a way one can directly link from the resources?

### ISSUE THREAD

**Issue by jadelkhoury** [OSLC/oslc-site-hugo#248]
For each of the resources on https://open-services.net/resources/index.html, one presses "details", which leads to a small page from which one links further to yet a third page.

Is it possible for "details" to simply point to the final content? 
In some cases, there is not much more to say on that middle page.

Concrete example: I want to update https://open-services.net/resources/developing-oslc-applications/

**Comment by berezovskyi** [comment]
Yes, I was thinking to actually make titles clickable instead: #240
