### ISSUE TITLE
Specification Pages Updates

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#27]
Latest plan:

1. http://open-services.net/specifications - Preserve this page, but this page should be significantly simplified to organize the specs in a simple list by the governing TC. 

2. http://open-services.net/specifications/requirements-management-2.0/ - this (for example) is the landing page for the document's governance page - this should redirect to the OASIS TC that now managing the page - probably the public URI.

3. http://open-services.net/bin/view/Main/RmSpecificationV2 - This is the link to the specification itself which should be redirected to either the migrated OASIS specification, or the PDF document in the TC's Documents folder, e.g., https://www.oasis-open.org/committees/document.php?document_id=61070&wg_abbrev=oslc-domains

@rersie thinks it would be a good idea to keep also a landing page for the next level e.g.:
http://open-services.net/specifications/requirements-management-2.0/
"Those pages should also be simplified and mostly point to the locations at the OASIS TC’s
Alternatively, if a good landing page already exists at the OASIS TC, the URI could be a direct redirect to that location."

**Comment by jamsden** [comment]
Re:

1. The page should provide an "at a glance" view of the specifications including their title, version, brief description, status link to TC and link actual document

2. Document links on the TC public pages are down a ways on the page under the section **Technical Work Produced by the Committee**. So having the actual document link (on the title of the document) in 1 above would be useful.

3. The link should stay on the cloned 2.x specifications until the migrated OASIS document is a Committee Specification.

Keeping the current landing page at http://open-services.net/specifications/requirements-management-2.0/ could be optional.  We have the summary page and the TC public home. That should be enough.

**Comment by brianking** [comment]
@jamsden - can you give a couple of example, to get started?

**Comment by jamsden** [comment]
Maybe a simple table with columns:

- Specification Title (with URL link to the latest published specification)
- Current status
- Governing OASIS TC name (with link to TC public page)
- Brief description (maybe optional - might make the table too big)
Make each column sortable so that users can easily navigate the table based on specification, workgroup or status.

**Comment by jailandrade** [comment]
I added a page to render the content from specifications and some styles for tables

**Comment by brianking** [comment]
@jamsden We are working on it here, it will be prettier!

https://oslc.github.io/specifications/

In terms of content, for the one item where have in there, OSLC 3.0, can you say:

* What is the "latest published specification" to link to in column 1?
* What is the "link to TC public page" in column 3?

As for status, the main thing I am concerned about is that because this will be manually updated it might get stale from time to time.

**Comment by brianking** [comment]
@jamsden 

The skeleton file for you to fill out is now checked in at:
https://github.com/OSLC/oslc-site-hugo/blob/master/content/specifications/_index.md

When live, it maps to:
https://oslc.github.io/specifications/

**Comment by brianking** [comment]
Initial table of OSLC specifications, status and links.
jamsden committed 13 hours ago
eb8d5b5

Changes are now on live test site: 
https://oslc.github.io/specifications/

**Comment by berezovskyi** [comment]
What is the reason for now publishing the 2.0 specs in HTML format by crawling the wiki as I suggested in https://github.com/OSLC/oslc-community/issues/3 ?

Publishing specs for open RESTful services in PDF seems ludicrous to me.

**Comment by jamsden** [comment]
Partly to ensure they can’t be (easily) edited - all edits should be done in the OASIS migrated specs. And partly for quick convenience. Other options can be entertained.

**Comment by berezovskyi** [comment]
I was under the same impression as @brianking: PDF gets preserved in OASIS, HTML is crawled for the website archive section.

**Comment by brianking** [comment]
@jamsden Are we good to go with this one?
http://oslc.co/specifications/

I'll open a separate issue to style the page to make it look prettier.

**Comment by jamsden** [comment]
I’d be happy to place HTML files on OASIS, perhaps in the Domains GitHub repo instead of the TC’s document library if we had them. I’m not wedded to the PDFs.

**Comment by berezovskyi** [comment]
1. Where is Core 2.0?
1. All 2.0 specs are still in PDF
1. https://tools.oasis-open.org/version-control/browse/wsvn/oslc-promcode/WorkingDrafts/promcode-interface-v1.0-wd01_Chapter3.docx should be converted to PDF.

I will upload the patch to see how I resolved §1 shortly. I actually found the TWiki source and discovered that Pandoc knows how to convert TWiki to Markdown.

**Comment by brianking** [comment]
Live at:
http://oslc.co/specifications/archive/core-2.0/
