### ISSUE TITLE
Case Studies Design

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#28]
The Case Studies section shows the value of OSLC technologies to possible stakeholders. It will consist of:

* Homepage section (covered in issue #7)
* 'Case Studies' site navigation item
* Case Studies page. This should either be a top-level page, or a sub-page of About (see issue #8)
* We may have sub-pages under the case studies page, depending on how much content we have.

The audiences we are targeting are:

* Vendors - why should current tools vendors support OSLC, and why is it complimentary to their business and not a threat
* Users (i.e. mostly companies) / System Integrators - why OSLC won't disrupt their workflow (continue using your datasources), and value added on top
* Developers

**Comment by gabrielfdac** [comment]
https://xd.adobe.com/view/3f063148-9a3a-4143-bf33-fdf74ae577e7

Case Studies Page design. For the homepage section refer to [#7](https://github.com/OSLC/oslc-site-hugo/issues/7).

Let me know what you guys think.

**Comment by brianking** [comment]
I like it, my only comment would be that maybe there are too many colours on the page.

It will also likely need different types of content than just text, but if we make the design simple enough then anything will fit.

@berezovskyi what do you think?

**Comment by m257645** [comment]
We might want to include the text "OSLC" as a minimum, or better still "Open Services Lifecycle Collaboration (OSLC)" where not too busy on pages where the logo appears rather than just having the logo itself.

**Comment by gabrielfdac** [comment]
I've updated the link with a all white background design. As far as different content overall anything should fit that design.

**Comment by brianking** [comment]
TODO: For @gabrielfdac 
* Add header image to design
* Add different types of content in each section to design, e.g. images/screenshots or other things typical to what a case study might look like.

**Comment by gabrielfdac** [comment]
Link has been updated with the latest requests. (Took the liberty of creating a "code snippet" style, which we could reuse on the Tutorials) Let me know what you think.

**Comment by brianking** [comment]
Looks great @gabrielfdac 

I'll open now a different issue to implement this.

**Comment by brianking** [comment]
Design done. Closing this now. We can open new issues for whatever is outstanding.
