### ISSUE TITLE
Abstract Menu and Social links to config.toml/theme.toml

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#34]
I notice these urls are now hard-coded. We should abstract them out. If you look at our current config.toml, you can see how the universal theme does it.

**Comment by brianking** [comment]
Any updates on this @jailandrade ?

**Comment by jailandrade** [comment]
Sorry, this was fixed a week ago, you can go to config.toml and update the menu and the changes will be reflected

**Comment by brianking** [comment]
Thanks for confirming. Closing this out.
