### ISSUE TITLE
Ecosystem Visualisation

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#35]
The OSLC Ecosystem is how all the different parts of the community fit together. e.g. open-services.net, OSLC at OASIS, Tool vendors, W3C, and so on.

There is an outdated visual representation in this post:
http://open-services.net/blog/all-systems-go-for-oslc-at-oasis/

**We need an updated version of this image**.

I started a presentation based on some slides that @rersch had. It still needs to be adapted/updated:

https://docs.google.com/presentation/d/1_CVGDS_gngN79hl1Gra-MfNGkwZQiVAFjmGxoTGC1H8/edit?usp=sharing

**Comment by brianking** [comment]
TODO:
* @brianking to come up with updated content for the image
* After that, @gabrielfdac will make a first pass at a new version

**Comment by brianking** [comment]
Adding @rersch for input, we talked about this when we met up recently in Munich.

**Comment by brianking** [comment]
So I think the 4 sections in the image still make sense, but the sub-content needs to be changed a bit.

**OSLC Member Section at OASIS**
Those sub-sections make sense to me, so maybe it can stay the same. @jamsden ?

**open-services.net**
The main thing to highlight here is that it is a community site. 
Some reasons why the site is important for the community and for OASIS.
* It aims to help increase the adoption of the OSLC specifications which are developed at OASIS.
*It does this by providing best practices, reference implementations, SDKs, and more.
* It gives the community a platform to discuss OSLC specific questions and share adoption examples.

Additionally, here are the main site features / sections of the upcoming new site:

* About - information about the mission/vision, value proposition for different audiences, people involved, software adopting OSLC, and an FAQ
* Resources - A collection of articles, videos, presentations, and tutorials on OSLC
* Contribute - Easy to understand guidance on how to contribute to specifications, add content to the site, join discussions and working groups, evangelize, and more.
* News - A blog with all the latest community updates

Might be worth highlighting Discourse.

**Approved Standard**
This is a bit hazy and needs to drawn out a bit. The OSLC Core standard is built upon the W3C LDP standard. 

**OSLC4Net**
This needs to be expanded to show the general software ecosystem, including out Github (https://github.com/OSLC).

@axelreichwein @rersch @jamsden @jadelkhoury @berezovskyi Any input on this one?

**Comment by gabrielfdac** [comment]
Hi all. Again I'm the one redesigning this image.

And right now I have some concerns:

1 - Content clutter. As of right now there's a bunch of content in the image already, even being just words. And from the discussion it seems that we want to explain things in a bit more detail. Which means more content. My concern is not only putting all this content in one image (in terms of how it will ultimately look) but also it just being confusing.

2 - Content clarity. Partially related to the one before. But here the concern is, from a perspective of someone who doesn't know about the community, will he(she) be able to understand this "ecosystem"? My guess is possible not.

Here is a suggestion:
How about giving proper attention/introduction to each of those sections before having the ecosystem image? Maybe we can have different paragraphs highlighting each section, with or without individual images, and then one representing it all?

Another suggestion, if we do decide on expanding the content, is to simplify what the visitor will see in the homepage and have a "know more" or "learn more" button leading to a page with explains it in detail. Perhaps "Ecosystem" could even be a sub-section of the about page.

In the meantime I have been sketching some ideas for layouts, trying to take the concerns mentioned before into considerations.

**Comment by brianking** [comment]
I like the idea of Ecosystem being a sub-section of the About section.

**Comment by berezovskyi** [comment]
I think it'd be great to provide a visualisation of the moving parts in the OSLC community.

What I think we wanted to say is the following:

1. OSLC specifications are produced by the OSLC TCs under OASIS
2. Whole process is guided by the Steering Committee
3. Specs are based on the W3C specs, esp. on W3C LDP spec
4. Public is welcome to comment on the OSLC spec drafts
5. some of the approved as well as draft OSLC spec are implemented in Eclipse Lyo SDK  
6. SDKs in for JS & .NET exist on OSLC Github
7. oslc.co is home to the OSLC community material & discussion but also to the user groups

I think we can split the ecosystem into the specification part (§1-4) and the community/SDK part (§5-7).

**Comment by brianking** [comment]
In general yes I agree with you @berezovskyi. I see 3 main parts:

* Specifications
* Software
* Community (everything else)

**Comment by gabrielfdac** [comment]
Hi everyone.

For this particular image I decided to take a low-level approach to design. This is a much more complex image with much greater message to it. Because of that taking a more intricate process where we're reviewing and sharing ideas along the design process would be highly beneficial.

With that in mind I made, for now, 3 layout mock-ups. The goal here is to try to find the best layout to the kind of message we want to share. For example the steering committee guides the entire communities process so perhaps is worth giving that aspect of the ecosystem a special attention. And in the perspective of layout we can do that by positioning, size and colors.

[Here](https://xd.adobe.com/view/4910cd5e-0c71-4ecd-9f3d-080472198a1c) are the mockups. I'll be updating this same link as we go along.

So mockup 1: 
**Pros**
- Gives extra attention to the steering community and gives this over-watch impression to it.
- Has great clarity of content. Things are well organized and not much clutter is present.
**Cons**
- Limits the amount of Sections to be displayed and overall content.

2:
**Pros**
- Gives this sense that everything is connected.
- More flexibility to the amount of "sections". 
**Cons**
- Vulnerable to content clutter.

3:
**Pros**
- Also gives a connectivity feel.
**Cons**
- Vulnerable to content clutter.
- Can only have text in the center of the image (greater circle).

So please take a moment to grab some feedback and share your initial thoughts, I could also make more of these if necessary.

**Comment by berezovskyi** [comment]
I like all options, but §2 looks most cohesive here, allowing various aspects to be centred around OSLC.

**Comment by brianking** [comment]
2 and 3 look the best for me, but I agree 2 would be the most cohesive.

**Comment by gabrielfdac** [comment]
Using option two I've updated the [link ](https://xd.adobe.com/view/4910cd5e-0c71-4ecd-9f3d-080472198a1c) with version 1 of the design.

First off apologies on the star wars references `:) I just wanted to use some text that was not lorem ipsum. I lean on you guys to provide the content.

I see this layout as a good way to provide a overview and with some icons/short sentences give a general idea of the ecosystem.

Also the idea here is to iterate on the design/content as much as necessary to get it right.

**Comment by brianking** [comment]
Ha, I know why you used Star Wars text, it looks like a tie fighter. As far as I am concerned you can proceed, this looks great.

**Comment by gabrielfdac** [comment]
I actually didn't think about that, but now that you said it it does look like it haha.

Well now it'd be great to have those texts, then I can adjust some of those icons to better fit the content. And then we'd be quite close to done.

**Comment by jamsden** [comment]
Does not need to be a live blockers.

**Comment by gabrielfdac** [comment]
No longer needed.
