### ISSUE TITLE
Implement About Theme

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#47]
Based on the design in issue #8, create the theme for the About landing page.

**Comment by brianking** [comment]
@jailandrade @LeoTrujillo Comments on what we have so far vs [design](https://xd.adobe.com/view/5d59ec65-69ae-431b-b35c-933d16e4c61d/).

* Please make About section 2 longer paragraphs, and not 3 short ones.
* A departure from the design, but the Steering Committee section should be named Governance. It should only have text, and link out to the Governance sub-page.
* While I like the Team section (it humanises the community), I'm not sure who we will be putting there yet. It might be better, for example, to have a similar section on the Contribute page that has a rotating highlight of community members. Any suggestions?
* Title of page has type. 'Abouts' should be 'About'.
* Sub-menu links at top of page should link to the sub-pages, and not to the anchors in the pages.
* For the FAQ section, if we have that on a sub-page, we need to come up with a good way of introducing it here. Any suggestions? One idea would just be to show one question, and then add a More... link.

Great stuff. Thanks!

cc @gabrielfdac

**Comment by jailandrade** [comment]
Sure, I will do this

**Comment by brianking** [comment]
Done a while ago. Closing.
