### ISSUE TITLE
Implement Resources Theme

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#48]
Based on the design in issue #10, create the theme for the Resources landing page.

**Comment by brianking** [comment]
@jailandrade @LeoTrujillo Comments on what we have so far vs design.

* Filter drop-down has 2 arrows (Firefox)
* Text in heading box does not span to align with section below. Section below may or may not also be too wide. We'll need to ensure we keep symmetry of sections across pages.
* Layout of footer items is not consistent with other pages.

Looks great in general!

**Comment by jailandrade** [comment]
@LeoTrujillo can you see this?

**Comment by brianking** [comment]
Outstanding issues:

* Filter drop-down has 2 arrows (Firefox)
![firefox_screenshot_2017-08-09t16-51-55 573z](https://user-images.githubusercontent.com/114116/29133464-daaa53ec-7d33-11e7-8fa1-c54002b557a9.png)
* Hover functionality on boxes not implemented

**Comment by LeoTrujillo** [comment]
@brianking now the search section looks good in firefox
<img width="416" alt="cap" src="https://user-images.githubusercontent.com/3343042/29144489-c589401e-7d1e-11e7-8fbd-d4fef93bab11.png">

**Comment by brianking** [comment]
Confirmed, the double arrow issue in Filter is fixed now.

**Comment by LeoTrujillo** [comment]
ok, sure I'm working on it

**Comment by brianking** [comment]
I think this has all been covered. Closing.
