### ISSUE TITLE
Implement Contribute Theme

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#50]
Based on the design in issue #9, create the theme for the Contribute landing page.

**Comment by brianking** [comment]
@jailandrade @LeoTrujillo Some thoughts on what we have now vs the design.

In general it looks good. We also have here the issue where the text in the header is not spanning width to match panel below.

NOTE that there is a new design pending on this, so don't spend too much time on this until we have it. More details are in the comments in issue #9. cc @gabrielfdac

**Comment by jailandrade** [comment]
@LeoTrujillo made this page before we found out that @gabrielfdac was going to change the design

**Comment by brianking** [comment]
@jailandrade @LeoTrujillo There is a new design available for this page.

**Comment by brianking** [comment]
On issue with the current version is that the banner image is not as tall as on other pages, leading to some inconsistency when navigating the site.

**Comment by jailandrade** [comment]
@brianking where is the new design for this page?

**Comment by brianking** [comment]
https://xd.adobe.com/view/1de62113-6a97-48e5-bb20-372b2351f069/

See also issue #9

**Comment by jailandrade** [comment]
I'm currently working on this

**Comment by jailandrade** [comment]
the latest changes for this issue are in master @brianking

**Comment by brianking** [comment]
Excellent @jailandrade I really like it so far. When we have content to put in, there might be further changes required.

**Comment by jailandrade** [comment]
still needs some tweaks for responsive design

**Comment by brianking** [comment]
@jailandrade Are we ok on responsive design now?

**Comment by jailandrade** [comment]
Yes, I forgot to comment on this issue.

**Comment by brianking** [comment]
Ok thanks, then closing.
