### ISSUE TITLE
Implement News Theme

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#51]
Based on the design in issue #13, create the theme for the News/Blog pages.

**Comment by brianking** [comment]
@jailandrade @LeoTrujillo Some thoughts on what we have now vs the design.

What we have now, the boxes, does not match the [design](https://xd.adobe.com/view/d999f9bc-f845-4de9-9dc6-80d397ebbcb6/) for the index page where posts are laid out in a more traditional format one under the other showing an abstract.

cc @gabrielfdac

**Comment by brianking** [comment]
On the index page, I am currently seeing the sidebar way down the page instead of being at the top.

![firefox_screenshot_2017-08-09t17-21-46 153z](https://user-images.githubusercontent.com/114116/29134760-12cf3676-7d38-11e7-93f1-41ad20918dcf.png)

**Comment by brianking** [comment]
Another issue. When I click the button to open a post, and then go back a back a page to the index, the button is stuck in selected (or hover) state different from other buttons.

**Comment by jailandrade** [comment]
working on it

**Comment by LeoTrujillo** [comment]
@brianking We have corrected that issue, now the news page looks like this...
<img width="1313" alt="cap" src="https://user-images.githubusercontent.com/3343042/29147066-585f9ebe-7d2a-11e7-8482-7da08386a4fb.png">

**Comment by brianking** [comment]
Thanks, the sidebar issue is now fixed. Still seeing the selected button issue.

**Comment by LeoTrujillo** [comment]
@brianking what do you mean with "selected button issue"?

**Comment by brianking** [comment]
Here are the steps to reproduce @LeoTrujillo 

1. Go to https://oslc.github.io/news/
2. Observe the colour of the first 'Continue Reading' button
3. Click on that button
4. After the post page loads, go back one page in the browser

Expected
The 'Continue Reading' button looks the same as before you clicked it

Actual
The 'Continue Reading' button text changes to a darker colour and is different from the other buttons.

**Comment by LeoTrujillo** [comment]
ok, I'm working on it

**Comment by LeoTrujillo** [comment]
@brianking Are you using a specific browser ?, because I followed those steps but it looks same for me, I mean, when I clicked the button and then go back I see the same colors in all buttons and I tested it in chrome, firefox and safari.
<img width="742" alt="ca" src="https://user-images.githubusercontent.com/3343042/29194059-8df80188-7ded-11e7-9d49-bd7275b1e769.png">

**Comment by brianking** [comment]
@LeoTrujillo Yes, I am using Firefox.

**Comment by gabrielfdac** [comment]
Updated the link with the new categories and search layout

**Comment by brianking** [comment]
https://xd.adobe.com/view/d999f9bc-f845-4de9-9dc6-80d397ebbcb6/

Looks good to me @gabrielfdac 

As for the individual post page at:

https://xd.adobe.com/view/7c0ebd40-d77c-4acd-8444-4555bc6da472/

... let's abandon the categories at the top there as well. Either we decide to have a sidebar on the post page as well, or we don't have categories and blog search there at all.

**Comment by jailandrade** [comment]
Ok, @LeoTrujillo is going to do the interface and I'm going to make the functionality

**Comment by brianking** [comment]
One outstanding task is that the posts on the homepage should match real posts.

**Comment by jailandrade** [comment]
This was a little tricky but now I think it's solved

**Comment by brianking** [comment]
Great! There are a few design tweaks needed, I will open another issue for that. Closing this.
