### ISSUE TITLE
Notification Bar

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#52]
We need a simple notification bar that goes on the very top of the site (all pages). It will be used for announcements mostly. 

So for example, it should have text something like this right now:

"This is a prototype site, and still a work in progress. For now please continue to refer to open-services.net as the source of information for the community"

open-services.net should be linked.

**Comment by jailandrade** [comment]
Ok, I'll do it

**Comment by jailandrade** [comment]
The component is ready and merged in master

**Comment by brianking** [comment]
I'm seeing the notification bar twice on all pages except the homepage.

![firefox_screenshot_2017-07-21t11-34-42 943z](https://user-images.githubusercontent.com/114116/28462113-0ef07a6a-6e1a-11e7-83ef-4a00cfc49b7b.png)

**Comment by jailandrade** [comment]
Last commit solve this https://github.com/OSLC/oslc-site-hugo/commit/6b7800fe811a6567f59fe464c20a8d91df59a9a9
