### ISSUE TITLE
About - Value Proposition Content

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/oslc-site-hugo#6]
Home -> About -> Why OSLC?

Explain why linked data in general is better than a standard combo of RDBMS+JSON. Target people who are somehow familiar with OOP/SQL and maybe even REST and are not convinced why our approach is better. Talk about linked data in the context of Big Data and raise a point of how important the technology is for keeping the future “data lakes” from turning into “data graveyards” (IMO).

See also:

* http://www.centre-for-bold-cities.nl/home
* https://blogs.thomsonreuters.com/answerson/exchange-magazine-big-open-linked-data/

Related to Case Studies, issue #28

**Comment by brianking** [comment]
A new proposed site page is a sub-page under About called 'Why OSLC?'.

Can we use the content on this page as a foundation?
http://open-services.net/wiki/communications/Why-should-you-care-about-OSLC/

**Comment by brianking** [comment]
Tagging @jamsden and @rersie for input here.

**Comment by berezovskyi** [comment]
I went over the content you linked to and provided comments. If you agree in general, I can put some text together:

https://docs.google.com/document/d/1-lHSS6BNfQfZfmm1_QBriXpid_9TFlTs-B7mpI9niiA/edit?usp=sharing

Just request access and I will approve it ASAP.

cc @jamsden @jadelkhoury

**Comment by brianking** [comment]
@berezovskyi In general I think your comments make sense. @axelreichwein should have a look as well.
Would you be comfortable just making a first pass at creating this page on the site? I can created the basic page for you to fill out.

**Comment by brianking** [comment]
I added the page if you want to run with it:
https://github.com/OSLC/oslc-site-hugo/blob/master/content/about/why.md

Live test under About at:
http://oslc.co/about/why/

**Comment by axelreichwein** [comment]
The "Why OSLC" section is super important. I think that it should be visible as a top-level menu item at the same level as About, etc..

I think that the "Why OSLC" section should provide different perspectives to answering the "Why OSLC" question. 

- Perspective 1) what technical challenge(s) does OSLC address, how does OSLC solve it 
- Perspective 2) what OSLC means for different roles (vendors, users)
- Perspective 3) what OSLC means for persons interested in well-known integration techniques such as ETL, knowledge graphs, and ESB/kafka-based integration architectures

**Comment by berezovskyi** [comment]
Yes, I think "Why OSLC" question shall be answered from multiple perspectives.

In my PR #179 I tried to look at the perspective 2), but maybe you can rework it to separate 1) from it and add a more advanced text for the perspective 3)?

**Comment by berezovskyi** [comment]
And I agree about the top-menu item!

**Comment by brianking** [comment]
Issue #186 opened to make this a top-level page and menu-item. We'll keep this issue about the content.
