### ISSUE TITLE
Deploy to oslc.co

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#68]
In issue #24 the domain transfer to a new registrar and host is nearly complete.

Once complete, we should deploy the site of oslc.co instead of it's current home at oslc.github.io.

**Comment by brianking** [comment]
@hectorsanchezmx and I chatted and he has agreed to take this one, at least for the part of enabling our droplet to host web content.

Initial requirements:
1. Keep discourse.oslc.co intact, with our Discourse installation
2. Setup our droplet to host web content, initially at oslc.co
3. Add simple welcome page to oslc.co. It should link, with a brief explanation of each to:
* open-services.net
* discourse.oslc.co
* https://github.com/OSLC/oslc-site-hugo

**Comment by hectorsanchezmx** [comment]
Discourse on http://discourse.oslc.co/
Website on http://oslc.co/

**Comment by brianking** [comment]
Excellent, @hectorsanchezmx that was fast!

Can you please update the following document on how to deploy to oslc.co. I've left a section at the end to be filled out.

https://github.com/OSLC/oslc-site-hugo/wiki/Contributing-Setup

**Comment by brianking** [comment]
Priority 1 @hectorsanchezmx

**Comment by hectorsanchezmx** [comment]
Instructions to deploy site to oslc.co are on the document.

**Comment by berezovskyi** [comment]
https://oslc.co is still failing to load.

**Comment by brianking** [comment]
@hectorsanchezmx will investigate.

**Comment by brianking** [comment]
We already have Letsencrypt ready to go (after the switch to open-services.net), and we can file a new issue for configuring Nginx for changes for the site to go live to open-services.net. So closing this one.
