### ISSUE TITLE
Add Text with Logo in Header

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#69]
Right now in the header, we have the logo only on the right hand side. I believe we need to have some text in there as well. There are at least 2 options:

1. Icon with text 'OSLC'
For example on Discourse we are using this logo
![image](https://user-images.githubusercontent.com/114116/29215807-bee21602-7eac-11e7-9fed-67bacede1296.png)

2. Icon with text 'Open Services for Lifecycle Collaboration'

I've no preference for either right now.

To consider:
* Should the text be text, or part of the image?
* How it will look on mobile

What are your thoughts @gabrielfdac ?

**Comment by gabrielfdac** [comment]
![logo and text](https://user-images.githubusercontent.com/16785479/29796719-62d484b6-8c18-11e7-915c-32e208c0825b.png)

Here it is. I used the same font we've used across the entire site (Open Sans). Let me know if there's anything I should change.

**Comment by brianking** [comment]
@gabrielfdac Please make a smaller image as we discussed, and integrate it into the site.

Please also make versions for Discourse, here are the specs:

* logo url - The logo image at the top left of your site, should be a wide rectangle shape. If left blank site title text will be shown.
* logo small url - The small logo image at the top left of your site, should be a square shape, seen when scrolling down. If left blank a home glyph will be shown.
* digest logo url - The alternate logo image used at the top of your site's email summary. Should be a wide rectangle shape. Should not be an SVG image. If left blank `logo_url` will be used.
* mobile logo url - The fixed position logo image used at the top left of your mobile site. Should be a square shape. If left blank, `logo_url` will be used. eg: http://example.com/uploads/default/logo.png
* favicon url - A favicon for your site, see http://en.wikipedia.org/wiki/Favicon, to work correctly over a CDN it must be a png
* apple touch icon url - Icon used for Apple touch devices. Recommended size is 144px by 144px.

**Comment by brianking** [comment]
This was done with recent home page imporovements by @gabrielfdac so thanks! Closing.

![firefox_screenshot_2017-10-23t15-25-41 887z](https://user-images.githubusercontent.com/114116/31897646-505afdd0-b817-11e7-85f5-57c89b26698a.png)
