### ISSUE TITLE
Fixed Navigation

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#70]
Let make the header, when the user scrolls, stay visible at the top of the page.

Further reading:
https://www.smashingmagazine.com/2012/09/sticky-menus-are-quicker-to-navigate/

**Comment by jailandrade** [comment]
sure! working on it

**Comment by LeoTrujillo** [comment]
Ok, the sticky menu is already in master branch

**Comment by brianking** [comment]
Prefect, thanks!
