### ISSUE TITLE
Limit number of News post on Homepage

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#71]
Currently on the homepage, we have multiple rows of sample posts. We need to limit it to the **latest 4 posts**. 

The design is here:
https://xd.adobe.com/view/f5a37d61-fe4c-4a78-a114-b75c9cc2010c/

**Comment by jailandrade** [comment]
this task is done

**Comment by brianking** [comment]
Great @jailandrade @LeoTrujillo next part of this task is for them to be actual posts from the news section.

**Comment by brianking** [comment]
Is this done ... showing actual posts? Also put some images in the sample posts, and not rotating images.

**Comment by jailandrade** [comment]
Is showing actual posts.

The images are obtained from the banner attribute in each markdown file. The images must be placed in the folder /static/img/oslc/

**Comment by brianking** [comment]
Ok done!
