### ISSUE TITLE
Banner on Contribute Page Issues

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#75]
There are 2 issues:

1. It is shorter than on other pages.

2. It has no background image like other pages.

**Comment by jailandrade** [comment]
Working on it

**Comment by jailandrade** [comment]
I merged the latest changes in master

**Comment by brianking** [comment]
Thanks @jailandrade 

There is still one issue. The text in the banner does not fill the correct width. Compare with Resources page for example.

![firefox_screenshot_2017-08-16t10-11-16 080z](https://user-images.githubusercontent.com/114116/29358739-699cdafa-827c-11e7-9fc1-1b1b21f91e00.png)

**Comment by jailandrade** [comment]
working on it

**Comment by brianking** [comment]
Now it is stretching too far, and it looks like the font size is different than in other banners.

Make sure consistent style classes are being used in all banners.

(testing on Firefox)

**Comment by jailandrade** [comment]
I uploaded a new version for this

**Comment by brianking** [comment]
Ok this is good enough for now. I will open new issues for anything else if needed. Closing.
