### ISSUE TITLE
Hyperlink blog post titles

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#76]
In addition to the continue reading buttons, I think it makes sense for blog post titles to link to the posts as well.

**Comment by LeoTrujillo** [comment]
@brianking I'm working on it

**Comment by brianking** [comment]
Thanks, tested it. Works good.

I wonder if it should change appearance onhover. @gabrielfdac what do you think?

**Comment by brianking** [comment]
Question also applies to blog posts on home page.

**Comment by jailandrade** [comment]
I applied a patch for the links @brianking

**Comment by brianking** [comment]
@LeoTrujillo Can you make the tweak we discussed at the end of call? When hovering over the post title, change the colour to a lighter shade of grey.

**Comment by LeoTrujillo** [comment]
sure

**Comment by LeoTrujillo** [comment]
I added the change

**Comment by brianking** [comment]
Great, thanks. Closing.
