### ISSUE TITLE
Document How To Create Site Content

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#77]
A guide for how the sire is structured, and how to add various different types of content.

- [x] Blog Post
- [ ] New Resource
- [x] FAQ Entry
- [x] [About Content](https://github.com/OSLC/oslc-site-hugo/issues/114#issuecomment-335522247)

**Comment by jailandrade** [comment]
I updated the guide and created some basic examples

**Comment by brianking** [comment]
Thank you for this @jailandrade, so good so far. However, I think we need to define some of the text you use to make things clearer, and to perhaps add more examples.

So some questions for you:

1. We should add a section at the start giving an introduction on what the document is about. For example, "This document gives instructions on how to create content for the site. We welcome contributions from the OSLC community, whether than be a new resource, a blog post, or something else that adds value. You can submit content via a pull request, and every request will be reviewed. If there are review comments, we will add them in the pull request. There is no guarantee that your content will be approved, and it is a good idea to get feedback on the idea first before writing the content. This can be done my opening a github issue, and using the label 'Content'."
2. In the first notions section talking about metadata, we should explain that some if it is used for display, and some not. We should add some example, and link to a help page explaining it if one exists.
3. "The file index.md in each folder is used for meta information...". We need to define what "meta information" is an means in this context.
4. For the contribute page, the file __index.md_ could benefit from better formatting. It is difficult to understand the sections on first glance. Please add a line break between each, and some comments in the code as well.
Are the _ct-*.md_ files used?
5. It is not clear to me the difference between list.html and single.html in a theme.
6. In general, we should add a section about 'hugo new' for generating content, for those who have hugo installed locally. We should call out what it can be used for on this site, for example creating a new blog post.

Later on, we'll extend the document for less technincal people and try to find ways for them to contribute content as well.

**Comment by brianking** [comment]
Please also add more information specifically about blog posts ... where to put author information, images so that they show up in previews, and so on.

**Comment by jailandrade** [comment]
I updated the user guide

**Comment by brianking** [comment]
Creating a news post:
https://github.com/OSLC/oslc-site-hugo/wiki/Creating-A-News-Post

**Comment by brianking** [comment]
Creating a FAQ entry:
https://github.com/OSLC/oslc-site-hugo/wiki/Adding-a-FAQ-Entry

**Comment by jamsden** [comment]
Should https://github.com/OSLC/oslc-site-hugo/wiki/Creating-A-News-Post be added to https://github.com/OSLC/oslc-site-hugo/blob/master/user_guide.md?

**Comment by jamsden** [comment]
Should https://github.com/OSLC/oslc-site-hugo/wiki/Contributing-Setup be copied or referenced in https://github.com/OSLC/oslc-site-hugo/blob/master/user_guide.md?

**Comment by berezovskyi** [comment]
The wiki is good enough
