### ISSUE TITLE
Hover on boxes on Resources page

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#78]
The boxes change on hover. Refer to the design for details.

**Comment by LeoTrujillo** [comment]
@brianking this issue has been finished

**Comment by brianking** [comment]
Thanks @LeoTrujillo 

I found one bug. When you hover over the Presentation box (3rd box on right of second row), the rows underneath jump / move position.

**Comment by LeoTrujillo** [comment]
ok @brianking working on it

**Comment by brianking** [comment]
Still jumping a little, but only in Firefox (not Chrome).

**Comment by LeoTrujillo** [comment]
ok, Testing and working on it

**Comment by LeoTrujillo** [comment]
@brianking I have tested the boxes in firefox, safari and chrome and now they look the same and they have no problems. Check it out and let me know if you have problems.

**Comment by brianking** [comment]
Fixed now!
