### ISSUE TITLE
Infinite Scroll on Resources Page

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#79]
On the Resources page, we will be adding multiple resources. To scale this the best, @gabrielfdac and I discussed infinite scroll being the best solution.

**Comment by LeoTrujillo** [comment]
Yes, I just tested with many items in the page and it support infinite scroll
@brianking

**Comment by brianking** [comment]
@LeoTrujillo do all the items load at once when the page loads, or do they lazily load as the user scrolls down? I believe we want the lazy load.

**Comment by brianking** [comment]
@LeoTrujillo is going to work on this today.

First check if there is anything native to Hugo, and check the Hugo Discourse forums for discussions on this.

If nothing can be found, next look at what lightweight JS libraries exist for this.

**Comment by LeoTrujillo** [comment]
the inifinite scroll is working now

**Comment by brianking** [comment]
Marking as fixed and closing. If there are any scroll issues, please open separately.
