### ISSUE TITLE
About Page Design

### ISSUE THREAD

**Issue by gabrielfdac** [OSLC/oslc-site-hugo#8]
https://xd.adobe.com/view/5d59ec65-69ae-431b-b35c-933d16e4c61d

About page design, as before happy to hear any feedback.

**Comment by berezovskyi** [comment]
Looks great actually! Doesn't have anything that shouldn't be there :)

**Comment by brianking** [comment]
That's a lot of my face on there!

I agree with Andrew, it looks great. However, what I envisioned for this page is that many of the sections would actually be sub-pages. It's ok perhaps to keep the sections as you have them, but have a shorter lead-in and then link to the page.

There would also be a sub-menu at the top of the page with the links to the various sub-pages. An example can be seen at http://onosproject.org/mission/.

**Comment by gabrielfdac** [comment]
I updated the link I sent before with the sub-menu.

**Comment by brianking** [comment]
I like it!

**Comment by brianking** [comment]
When user is on any page in About, both that sub-menu item and the main About menu item should be highlighted.

**Comment by brianking** [comment]
In general this looks great @gabrielfdac and has been implemented well. Anything outstanding?

**Comment by brianking** [comment]
One thing that is missing that is on other pages is an image banner. Do you think it is needed?

**Comment by gabrielfdac** [comment]
@brianking I wouldn't say it's needed but it would definitely show some consistency across the pages. The reason why I didn't put any is that since we'll be having subpages we'd have to discuss if we want a single one for all subpages or individual ones for each. Let me know.

**Comment by brianking** [comment]
TODO: @gabrielfdac to come up with sample design with header images to compare. Not a priority.

**Comment by gabrielfdac** [comment]
I just updated the link with all of the sub-pages. The first two sub-pages have Hero's and the other 3 don't, I've done that so that it's easy to compare.

Also this time around I used the prototyping abilities of Adobe XD. So you can actually click the sub-menu as if they were actually links or the menu on the bottom of the page (as well as you keyboard arrows) to navigate. Any questions about it, let me know.

**Comment by brianking** [comment]
@gabrielfdac I like how the page you are on is selected by an underline in the menu.

If we do go with separate pages, then we're going to have to be very clear on the content .. the About page has the short version, and the individual pages have the long version. But that's my job. I'll have a better feeling for this soon.

@jail Does the current content structure allow for a sub-page of About?

**Comment by brianking** [comment]
Closing this now. We can open new issues for whatever is outstanding.
