### ISSUE TITLE
Lines under headers in Resources section

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#82]
On the homepage, there are different boxes in the Resources section, e.g. Tutorials.

The headers in these sections should have a horizontal line under them. Refer to the design for details.

**Comment by LeoTrujillo** [comment]
Woking on it

**Comment by LeoTrujillo** [comment]
@brianking that change is already in master branch
<img width="1440" alt="c" src="https://user-images.githubusercontent.com/3343042/29319821-e7741282-819a-11e7-8202-a7dc6356684c.png">

**Comment by brianking** [comment]
Looks good, thanks. Closing.
