### ISSUE TITLE
Contribute Page Design

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#9]
From the site plan:

**Overview**
This is arguably the most important section, for what is a community without active participants. Right in the forefront should be clear calls to action, that both meet the needs of different types of contributors and that are the most impactful to the community.
 
**Sections**
* Contribute
  * Development - how to contribute to coding
    * Need to point to OSLC Github, and surface up some interesting projects
    * Lyo should continue to be the "official" OSLC code, but we should open things up on Git. Maybe have our own Git repos, but also encourage people to incorporate OSLC tags. E.g.     * https://github.com/search?utf8=%E2%9C%93&q=oslc&type=
  * Usergroups
    * Describe use cases, talk implementations, new domain proposals, etc.
  * Add Content
    * Submit videos, links, articles, etc.
  * Evangelise (Present OSLC)
    * At conferences
    * Internally in their work environment
  * Share
    * Support us on social media by joining our channels and sharing items
    * Create content for your own channels and tag with #oslc
* Communications
  * Ways to join the conversation
    * Slack
    * Forums
* Tools
  * Tools for what? Might be integrated into Contribute section.
* Specifications
  * A summary of specification work, and then link out to OASIS

 
**Maps To**
Current Participate page.
http://open-services.net/participate/
 
**Examples**
* http://onosproject.org/contribute/
* https://www.ansible.com/community
* http://opencord.org/contribute/
* https://community.ubuntu.com/contribute/

**Comment by brianking** [comment]
As you can see some of the sections are not fully thought through yet, but we have enough to get the basic design down and we can figure out after how to best present each opportunity.

**Comment by gabrielfdac** [comment]
https://xd.adobe.com/view/1de62113-6a97-48e5-bb20-372b2351f069/

Here the design for the Contribute page. I took a very simple approach to it. Let me know if we can improve it in any way.

**Comment by brianking** [comment]
I like it in general. The icons have the potential to convey a lot of meaning.

However, thinking about this some more I think it would be nice to have some sort of grid approach. It would be some sort of combination of these two pages:

https://theodi.org/get-involved
https://www.ansible.com/community

So they would be boxes, and they all don't have to the the same size (see ODI site). This will allow us to rotate opportunities so than in some weeks we have featured opportunities in the bigger boxes. The boxes themselves however would contain significant content, similar to the Ansible boxes. No hover effect is needed.

Note that we need to keep mobile in mind (responsiveness) as we design this, so maybe in that mode the boxes would just line up one under the other.

**Comment by gabrielfdac** [comment]
Ok, I'll see what I can do about it

**Comment by gabrielfdac** [comment]
I just updated the design for the contribute page on the link above.

Let me know if that's more like what you had in mind.

**Comment by brianking** [comment]
Again, I think there might be too many colours here that could be a distraction from the content. The boxes also seem too small. We'll need sections on the page that can hold more and different types of content.

**Comment by gabrielfdac** [comment]
I updated the link with a new take on it. Let me know your thoughts

**Comment by brianking** [comment]
Yes this much better @gabrielfdac and closer to the vision I had! Good work.

**Comment by brianking** [comment]
Closing this now. We can open new issues for whatever is outstanding.
