### ISSUE TITLE
Change link in Resources section on homepage

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#90]
Current:
* The whole top part of the Resoruces section on the homepage is a link, going to /resources/.

Change to:
* Remove the link from the section
* Add 'See all...' text just after the description, and make that the link. Make sure it is styled to look like a link.

The [design](https://xd.adobe.com/view/f5a37d61-fe4c-4a78-a114-b75c9cc2010c/) shows what it looks like.

**Comment by LeoTrujillo** [comment]
@brianking , working on it

**Comment by brianking** [comment]
Works for me, please close if you have completed the work.
