### ISSUE TITLE
Banner Changes on News page

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#91]
2 changes:

1. Change title from all uppercase to 'News'.
2. To be consistent with other pages such as Resources, add a description. Make sure it spans the appropriate width. The text should be as follows.

The latest happenings in the OSLC community. This could be site announcements, software news, stories from the wider OSLC ecosystem, and more.

**Comment by jailandrade** [comment]
Ready to test

**Comment by brianking** [comment]
Looks good, closing!
