### ISSUE TITLE
Search for Resources page

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#96]
Implement the search box functionality for the Resources page.

Check first for a search function that might be native to Hugo, and for relevant discussions on the Hugo Discourse forums.

**Comment by jailandrade** [comment]
After investigating more options, I found this https://github.com/gohugoio/hugo/blob/4c220c4ac2302b6c0a535c1099f2d393d57049c6/docs/content/tools/search.md

I'm looking in every solution

**Comment by jailandrade** [comment]
The search is working now, but now we need to figure out some way how to generate a json file with all the posts from resources in every deployment, we have a solution in the static-src folder that could work but we  need to test in production mode

**Comment by brianking** [comment]
I like it, great job!

We have to ask ourselves if:
a) Search includes text and filter
b) Search is text only (we would need to move the search button over beside the search boc), and filtering is a separate function that just shows posts from each category

Right now it is implemented as number 1, and that seems like the right choice.

At the moment however it does not work like that. Steps to reproduce:

1. Filter by Podcast. 1 item appears
2. Add the search text 'ad' (without quotes)

Expected:
Only one item stays, the Podcast

Actual:
A second item appears, which is an Article. So even with Podcast in the filter list, an Article appears.

**Comment by brianking** [comment]
Ah, I see your comment @jailandrade in issue #97 about search and filtering together. Will followup there.

**Comment by brianking** [comment]
@jailandrade has the generation of the json file been worked out yet? If so, can you explain how it works.

**Comment by jailandrade** [comment]
Yes, for this you need to have nodejs installed. 

1. Go to the static-src folder
2. Run `npm install`
3. Run `node search.js`

Now you have a file `static/resources/resources.json` ready to be searched

**Comment by brianking** [comment]
Is it a one-time thing, or needs to be done anytime there is new content?

**Comment by jailandrade** [comment]
It needs to be done anytime there is new content, I think we can automatize with the deployment.

**Comment by brianking** [comment]
Closing, if there are any fixes needed here we can open new issues.
