### ISSUE TITLE
Filtering for Resources Page

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#97]
Implement the filtering functionality for the Resources page.

Check first for something native to Hugo, and for relevant discussions on the Hugo Discourse forums.

Note that the [current Resources page](http://open-services.net/resources/) already has this, but the solution just loads a separate sub-page for each type. It might be more elegant for us to filter on the same page. 

It has to work nicely with the search function. Should we allow both to be active, or just one at a time? i.e. can the user search on filtered items only, and vice versa?

**Comment by jailandrade** [comment]
We can replicate the current behavior of the old site and I think it's the simplest solution.

But if we want to be more creative we can use the search implementation in a different way. I don't think it's a good idea to filter and search at the same time but if the search works the filter can work too

**Comment by jailandrade** [comment]
Search and filter working now, not at the same time, but working

**Comment by brianking** [comment]
Closing, if there are any fixes needed here we can open new issues.
