### ISSUE TITLE
Categories on News Page

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#99]
There are a few parts to this:

* Investigate how Hugo does categories
* Investigate how to create them, and how to add a category in a post
* Create the initial set of 3-4 categories for OSLC, and add them to the current sample posts
* Add a categories dropdown to the blog page sidebar, and implement filtering

**Comment by jailandrade** [comment]
I just upload some changes for this task

**Comment by brianking** [comment]
@jailandrade the UI to be implemented for this is now ready at:

https://xd.adobe.com/view/d999f9bc-f845-4de9-9dc6-80d397ebbcb6/

**Comment by LeoTrujillo** [comment]
I'm working with the Search form interface

**Comment by LeoTrujillo** [comment]
The Search form interface in news page is done

**Comment by brianking** [comment]
UI looks of, but in the filter menu clicking on the arrow does not work. It only works if you click on the text. Using Firefox. It looks like it needs styling as well, as the items are very close together in the dropdown.

Also, the categories need to me moved from the bottom of the sidebar into the dropdown and the functionality hooked up.

**Comment by jailandrade** [comment]
I just implemented the search for the news, I didn't integrate the categories select function because I have doubts about how this will be works

**Comment by brianking** [comment]
What doubts do you have @jailandrade ?

I think we should keep it simple.

* Search is for text search only in the blog. It does not interact with categories
* Selecting a category shows all post from that category

This is how most blogs I know work with these features.

The UI might need to be tweaked to make these more separate.

**Comment by jailandrade** [comment]
So, I think we need to change the style, I'll do it

**Comment by jailandrade** [comment]
This task it's also finished

**Comment by brianking** [comment]
Closing. There is a bug with the dropdown style, I will open a new issue for that.
